{
    package internal

    type ErrList = errList
    type ParserError = parserError
}

AST <- init docI:PackageDoc EMPTY_LINE* pkgI:Package EMPTY_LINE* scopeI:GlobalScope EMPTY_LINE* EOF {
    f := file(c)
    f.PackageDoc = optCast[[]*ast.DevComment](docI)
    f.PackageDirective = optCast[*ast.PackageDirective](pkgI)
    f.Scope = scopeI.(*ast.Scope)
    return f.AST, nil
}

init <- #{
    newState(c)
    return nil
}
