linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - dupword
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - loggercheck
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tenv
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  godot:
    exclude:
      - ^\s*.+:.+$
      - ^\s*(?:=+|/+|-+|\++)
      - ^\s*\w+$
  unparam:
    check-exported: true
  gocritic:
    disabled-checks:
      - singleCaseSwitch

  errcheck:
    exclude-functions:
      - github.com/mavolin/corgi/file/fileutil.Walk

issues:
  exclude-rules:
    - path: ^test/
      linters: [unused]