version: "2"

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - dupword
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocritic
    - godot
    - gosec
    - govet
    - importas
    - ineffassign
    - intrange
    - loggercheck
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
    gocritic:
      disabled-checks:
        - singleCaseSwitch
    godot:
      exclude:
        - ^\s*\p{Ll}           # Exclude lowercase comments
        - ^\s*(?:=+|/+|-+|\++) # Exclude lines that are not identifiers
        - ^\s*\w+$             # Exclude single-word identifiers
        - ^(\s*\p{Lu}+)+$      # Exclude sectioning comments (all uppercase)
        - '[\w\d]:\s+'         # Exclude colons
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: '^file/switches/functions\.go$'
        linters: [gocritic]
        text: '^captLocal:'
      - path: '^load/analyze/internal/'
        linters: [revive]
        text: '^var-naming:'
      - path: '^load/analyze/internal/analyze/'
        linters: [unused]
      - path: '^load/analyze/internal/candidate/switches\.go$'
        linters: [gocritic]
        text: '^captLocal:'
      - path: '[^/]+_test.go$'
        linters:
          - errcheck
          - unparam
      - path: '[^/]+_test\.go$'
        linters: [revive]
        text: "^var-naming:"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
