before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/corgi
    ldflags:
      - -X github.com/mavolin/corgi/internal/meta.Version={{.Tag}}
      - -X github.com/mavolin/corgi/internal/meta.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: 'checksums.txt'
changelog:
  use: github
  sort: asc
  groups:
    - title: 💥 Breaking Changes
      regexp: '^.*(feat|fix|revert|refactor)(\([^)]+\))?!:'
      order: 0
    - title: ⚡ Features
      regexp: '^.*feat(\([^)]+\))?:'
      order: 1
    - title: 🪲 Bug Fixes
      regexp: '^.*fix(\([^)]+\))?:'
      order: 2
    - title: 🏎 Performance Improvements
      regexp: '^.*perf(\([^)]+\))?:'
      order: 3
    - title: ✏ Others
      order: 999
  filters:
    exclude:
      - ^build
      - ^ci
      - ^docs
      - ^style
      - ^test
