//go:build generate

package charref

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"slices"
	"strings"
	"testing"
)

const out = "chars.go"

func TestGenerate(t *testing.T) {
	pkg := os.Getenv("GOPACKAGE")
	if pkg == "" {
		t.Fatal("GOPACKAGE is not set")
	}

	charRefs, err := loadCharacterReferences()
	if err != nil {
		t.Fatal(err)
	}

	f, err := os.Create(out)
	if err != nil {
		t.Fatalf("output file: %s", err)
	}
	defer f.Close()

	writeFile(f, pkg, charRefs)
}

type characterReference struct {
	Name  string
	Runes string
}

const entitiesURL = "https://html.spec.whatwg.org/entities.json"

func loadCharacterReferences() ([]characterReference, error) {
	resp, err := http.Get(entitiesURL)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch entities.json: %w", err)
	}

	entMap := make(map[string]struct {
		Characters string `json:"characters"`
	})

	err = json.NewDecoder(resp.Body).Decode(&entMap)
	if err != nil {
		return nil, fmt.Errorf("failed to decode entities.json: %w", err)
	}
	_ = resp.Body.Close()

	charRefs := make([]characterReference, 0, len(entMap))

	for name, obj := range entMap {
		if !strings.HasPrefix(name, "&") || !strings.HasSuffix(name, ";") {
			continue
		}
		name = name[len("&") : len(name)-len(";")]

		charRefs = append(charRefs, characterReference{
			Name:  name,
			Runes: obj.Characters,
		})
	}

	slices.SortFunc(charRefs, func(a, b characterReference) int {
		return strings.Compare(a.Name, b.Name)
	})

	return charRefs, nil
}

func writeFile(w io.Writer, pkg string, charRefs []characterReference) {
	fmt.Fprintf(w, "package %s\n", pkg)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// Code generated by go test -run=Generate -tags generate; DO NOT EDIT.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// Chars returns the character sequence represented by the passed named")
	fmt.Fprintln(w, "// character reference.")
	fmt.Fprintln(w, "//")
	fmt.Fprintln(w, "// name must be stripped of the leading '&' and the trailing ';'.")
	fmt.Fprintln(w, "func Chars(name string) string {")
	fmt.Fprintln(w, "\tswitch name {")
	for _, ref := range charRefs {
		fmt.Fprintf(w, "\tcase %q:\n", ref.Name)
		fmt.Fprintf(w, "\t\treturn %q\n", ref.Runes)
	}
	fmt.Fprintln(w, "\tdefault:")
	fmt.Fprintln(w, "\t\treturn \"\"")
	fmt.Fprintln(w, "\t}")
	fmt.Fprintln(w, "}")
}
