package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"slices"
	"strings"
)

const entitiesURL = "https://html.spec.whatwg.org/entities.json"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	charRefs, err := loadCharacterReferences()
	if err != nil {
		return err
	}

	if err = genMap(charRefs); err != nil {
		return err
	}

	return nil
}

type characterReference struct {
	Name  string
	Runes string
}

func loadCharacterReferences() ([]characterReference, error) {
	resp, err := http.Get(entitiesURL)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch entities.json: %w", err)
	}

	entMap := make(map[string]struct {
		Characters string `json:"characters"`
	})

	err = json.NewDecoder(resp.Body).Decode(&entMap)
	if err != nil {
		return nil, fmt.Errorf("failed to decode entities.json: %w", err)
	}
	_ = resp.Body.Close()

	charRefs := make([]characterReference, 0, len(entMap))

	for name, obj := range entMap {
		if !strings.HasPrefix(name, "&") || !strings.HasSuffix(name, ";") {
			continue
		}
		name = name[1 : len(name)-1]

		charRefs = append(charRefs, characterReference{
			Name:  name,
			Runes: obj.Characters,
		})
	}

	slices.SortFunc(charRefs, func(a, b characterReference) int {
		return strings.Compare(a.Name, b.Name)
	})

	return charRefs, nil
}

func genMap(charRefs []characterReference) error {
	const (
		packageName = "charref"
		outFile     = "chars.go"
	)

	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}

	fmt.Fprintf(f, "package %s\n", packageName)
	fmt.Fprintln(f)
	fmt.Fprintln(f, "// Code generated by tools/codegen/charrefexport; DO NOT EDIT.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "// Chars returns the character sequence represented by the passed named")
	fmt.Fprintln(f, "// character reference.")
	fmt.Fprintln(f, "//")
	fmt.Fprintln(f, "// name must be stripped of the leading '&' and the trailing ';'.")
	fmt.Fprintln(f, "func Chars(name string) string {")
	fmt.Fprintln(f, "\tswitch name {")
	for _, ref := range charRefs {
		fmt.Fprintf(f, "\t\tcase %q:\n", ref.Name)
		fmt.Fprintf(f, "\t\t\treturn %q\n", ref.Runes)
	}
	fmt.Fprintln(f, "\t\tdefault:")
	fmt.Fprintln(f, "\t\t\treturn \"\"")
	fmt.Fprintln(f, "\t}")
	fmt.Fprintln(f, "}")

	return f.Close()
}
