package main

import (
	"errors"
	"fmt"
	"io"
	"os"
)

func main() {
	args, err := resolveArgs()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	if err := run(args); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

type args struct {
	Package string

	Out string
}

func resolveArgs() (*args, error) {
	var a args

	a.Package = os.Getenv("GOPACKAGE")
	if a.Package == "" {
		return nil, errors.New("GOPACKAGE is not set")
	}

	if len(os.Args) != 2 {
		return nil, fmt.Errorf("expected exactly one argument, got %d", len(os.Args)-1)
	}

	a.Out = os.Args[1]
	return &a, nil
}

func run(args *args) error {
	charRefs, err := loadCharacterReferences()
	if err != nil {
		return err
	}

	f, err := os.Create(args.Out)
	if err != nil {
		return fmt.Errorf("output file: %w", err)
	}
	defer f.Close()

	writeFile(f, args.Package, charRefs)
	return nil
}

func writeFile(w io.Writer, pkg string, charRefs []characterReference) {
	fmt.Fprintf(w, "package %s\n", pkg)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// Code generated by tools/codegen/charrefexport; DO NOT EDIT.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// Chars returns the character sequence represented by the passed named")
	fmt.Fprintln(w, "// character reference.")
	fmt.Fprintln(w, "//")
	fmt.Fprintln(w, "// name must be stripped of the leading '&' and the trailing ';'.")
	fmt.Fprintln(w, "func Chars(name string) string {")
	fmt.Fprintln(w, "\tswitch name {")
	for _, ref := range charRefs {
		fmt.Fprintf(w, "\tcase %q:\n", ref.Name)
		fmt.Fprintf(w, "\t\treturn %q\n", ref.Runes)
	}
	fmt.Fprintln(w, "\tdefault:")
	fmt.Fprintln(w, "\t\treturn \"\"")
	fmt.Fprintln(w, "\t}")
	fmt.Fprintln(w, "}")
}
