package analyze

import (
	"github.com/mavolin/corgi/v2/escape/attrtype"
	"github.com/mavolin/corgi/v2/escape/elemtype"
	"github.com/mavolin/corgi/v2/file"
	"github.com/mavolin/corgi/v2/file/ast"
)

// Code generated by go test -run GenerateAssertions -tags generate; DO NOT EDIT.

//go:generate go test -run GenerateAssertions -tags generate

var get = struct {
	Attribute struct {
		Value                 func(z *analyzer, __r *file.Attribute) file.ResolvedValue
		Forwarded             func(z *analyzer, __r *file.Attribute) file.Analysis[bool]
		Receivers             func(z *analyzer, __r *file.Attribute) file.Analysis[file.SliceRef[ast.AttributeReceiver]]
		ReceivingElementSpecs func(z *analyzer, __r *file.Attribute) file.Analysis[file.SliceRef[*file.ElementSpec]]
		Type                  func(z *analyzer, __r *file.Attribute) file.Analysis[attrtype.Type]
	}
	Block struct {
		Required                func(z *analyzer, __r *file.Block) (a file.Analysis[bool])
		Forwarded               func(z *analyzer, __r *file.Block) (a file.AnalysisWithReason[*file.BlockInstance])
		ForwardsAttributes      func(z *analyzer, __r *file.Block) (a file.Analysis[bool])
		CannotForwardAttributes func(z *analyzer, __r *file.Block) (a file.AnalysisWithReason[*file.BlockInstance])
		ElementType             func(z *analyzer, __r *file.Block) (a file.Analysis[elemtype.Type])
		MostRestrictiveElement  func(z *analyzer, __r *file.Block) (a file.AnalysisWithReason[ast.ContainingElement])
	}
	BlockInstance struct {
		Forwarded               func(z *analyzer, __r *file.BlockInstance) file.Analysis[bool]
		ContainingElements      func(z *analyzer, __r *file.BlockInstance) file.Analysis[file.SliceRef[ast.ContainingElement]]
		ContainingElementSpecs  func(z *analyzer, __r *file.BlockInstance) file.Analysis[file.SliceRef[*file.ElementSpec]]
		CannotForwardAttributes func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.AttributeInhibitor]
		ElementType             func(z *analyzer, __r *file.BlockInstance) (a file.Analysis[elemtype.Type])
		MostRestrictiveElement  func(z *analyzer, __r *file.BlockInstance) (a file.AnalysisWithReason[ast.ContainingElement])
		ForwardsAttributes      func(z *analyzer, __r *file.BlockInstance) (a file.Analysis[bool])
		DefaultOverwritten      func(z *analyzer, __r *file.BlockInstance, cc *file.ComponentCall) bool
		Default                 struct {
			AcceptsAttributes              func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.AndPlaceholderWriter]
			ForwardsReceivedAttributes     func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.AndPlaceholderWriter]
			ElementsWithAndPlaceholder     func(z *analyzer, __r *file.BlockInstance) file.Analysis[file.SliceRef[ast.AttributeReceiver]]
			ElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.BlockInstance) file.Analysis[file.SliceRef[*file.ElementSpec]]
			ForwardsAttributes             func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.AttributeWriter]
			WritesContent                  func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.ContentWriter]
			WritesElements                 func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.ElementWriter]
		}
	}
	BlockSetter struct {
		WritesAndPlaceholder   func(z *analyzer, __r *file.BlockSetter) (a file.AnalysisWithReason[*file.BlockSetterInstance])
		ForwardsAndPlaceholder func(z *analyzer, __r *file.BlockSetter) (a file.AnalysisWithReason[*file.BlockSetterInstance])
		ForwardsAttributes     func(z *analyzer, __r *file.BlockSetter) (a file.AnalysisWithReason[*file.BlockSetterInstance])
		WritesContent          func(z *analyzer, __r *file.BlockSetter) (a file.AnalysisWithReason[*file.BlockSetterInstance])
		WritesElements         func(z *analyzer, __r *file.BlockSetter) (a file.AnalysisWithReason[*file.BlockSetterInstance])
	}
	BlockSetterInstance struct {
		AcceptsAttributes          func(z *analyzer, __r *file.BlockSetterInstance) file.AnalysisWithReason[ast.AndPlaceholderWriter]
		ForwardsReceivedAttributes func(z *analyzer, __r *file.BlockSetterInstance) file.AnalysisWithReason[ast.AndPlaceholderWriter]
		ForwardsAttributes         func(z *analyzer, __r *file.BlockSetterInstance) file.AnalysisWithReason[ast.AttributeWriter]
		WritesContent              func(z *analyzer, __r *file.BlockSetterInstance) file.AnalysisWithReason[ast.ContentWriter]
		WritesElements             func(z *analyzer, __r *file.BlockSetterInstance) file.AnalysisWithReason[ast.ElementWriter]
	}
	Component struct {
		Circular                                func(z *analyzer, __r *file.Component) bool
		AlwaysAcceptsAttributes                 func(z *analyzer, __r *file.Component) file.AnalysisWithReason[ast.AndPlaceholderWriter]
		AlwaysForwardsReceivedAttributes        func(z *analyzer, __r *file.Component) file.AnalysisWithReason[ast.AndPlaceholderWriter]
		AlwaysForwardsAttributes                func(z *analyzer, __r *file.Component) file.AnalysisWithReason[ast.AttributeWriter]
		AlwaysWritesContent                     func(z *analyzer, __r *file.Component) file.AnalysisWithReason[ast.ContentWriter]
		AlwaysWritesElements                    func(z *analyzer, __r *file.Component) file.AnalysisWithReason[ast.ElementWriter]
		PermanentElementsWithAndPlaceholder     func(z *analyzer, __r *file.Component) file.Analysis[file.SliceRef[ast.AttributeReceiver]]
		PermanentElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.Component) file.Analysis[file.SliceRef[*file.ElementSpec]]
		CouldAcceptAttributes                   func(z *analyzer, __r *file.Component) (a file.AnalysisWithReason[ast.AndPlaceholderWriter])
		CouldForwardReceivedAttributes          func(z *analyzer, __r *file.Component) (a file.AnalysisWithReason[ast.AndPlaceholderWriter])
	}
	ComponentArgument struct {
		Value func(z *analyzer, __r *file.ComponentArgument) file.ResolvedValue
	}
	ComponentParameter struct {
		InferredType  func(z *analyzer, __r *file.ComponentParameter) file.Analysis[file.Type]
		AttributeType func(z *analyzer, __r *file.ComponentParameter) file.Analysis[attrtype.Type]
		AttributeName func(z *analyzer, __r *file.ComponentParameter) file.Analysis[string]
		ResolvedType  func(z *analyzer, __r *file.ComponentParameter) file.Analysis[file.Type]
		Required      func(z *analyzer, __r *file.ComponentParameter) bool
	}
	ComponentCall struct {
		ReceivesAttributes                func(z *analyzer, __r *file.ComponentCall) file.AnalysisWithReason[ast.AttributeWriter]
		ReceivesAndPlaceholder            func(z *analyzer, __r *file.ComponentCall) file.AnalysisWithReason[ast.AndPlaceholderWriter]
		ElementsWithAndPlaceholder        func(z *analyzer, __r *file.ComponentCall) file.Analysis[file.SliceRef[ast.AttributeReceiver]]
		ElementSpecsWithAndPlaceholder    func(z *analyzer, __r *file.ComponentCall) file.Analysis[file.SliceRef[*file.ElementSpec]]
		AcceptsAttributes                 func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.AndPlaceholderWriter])
		ForwardsAcceptedAttributes        func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.AndPlaceholderWriter])
		ForwardsAndPlaceholder            func(z *analyzer, __r *file.ComponentCall) (a file.Analysis[bool])
		ForwardsReceivedAndPlaceholder    func(z *analyzer, __r *file.ComponentCall) file.AnalysisWithReason[ast.AndPlaceholderWriter]
		BlockSetterForwardsAndPlaceholder func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[*file.BlockSetter])
		ForwardsAttributes                func(z *analyzer, __r *file.ComponentCall) (a file.Analysis[bool])
		ComponentForwardsAttributes       func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.AttributeWriter])
		ForwardsReceivedAttributes        func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.AttributeWriter])
		BlockSetterForwardsAttributes     func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[*file.BlockSetter])
		WritesContent                     func(z *analyzer, __r *file.ComponentCall) (a file.Analysis[bool])
		ComponentWritesContent            func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.ContentWriter])
		BlockSetterWritesContent          func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[*file.BlockSetter])
		WritesElements                    func(z *analyzer, __r *file.ComponentCall) (a file.Analysis[bool])
		ComponentWritesElements           func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.ElementWriter])
		BlockSetterWritesElements         func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[*file.BlockSetter])
	}
	ElementSpec struct {
		Circular func(z *analyzer, __r *file.ElementSpec) bool
		Type     func(z *analyzer, __r *file.ElementSpec) file.Analysis[elemtype.Type]
	}
}{
	Attribute: struct {
		Value                 func(z *analyzer, __r *file.Attribute) file.ResolvedValue
		Forwarded             func(z *analyzer, __r *file.Attribute) file.Analysis[bool]
		Receivers             func(z *analyzer, __r *file.Attribute) file.Analysis[file.SliceRef[ast.AttributeReceiver]]
		ReceivingElementSpecs func(z *analyzer, __r *file.Attribute) file.Analysis[file.SliceRef[*file.ElementSpec]]
		Type                  func(z *analyzer, __r *file.Attribute) file.Analysis[attrtype.Type]
	}{
		Value: func(z *analyzer, __r *file.Attribute) file.ResolvedValue {
			require.Attribute.Value(z, __r)
			return __r.Value
		},
		Forwarded: func(z *analyzer, __r *file.Attribute) file.Analysis[bool] {
			require.Attribute.Forwarded(z, __r)
			return __r.Forwarded
		},
		Receivers: func(z *analyzer, __r *file.Attribute) file.Analysis[file.SliceRef[ast.AttributeReceiver]] {
			require.Attribute.Receivers(z, __r)
			return __r.Receivers
		},
		ReceivingElementSpecs: func(z *analyzer, __r *file.Attribute) file.Analysis[file.SliceRef[*file.ElementSpec]] {
			require.Attribute.ReceivingElementSpecs(z, __r)
			return __r.ReceivingElementSpecs
		},
		Type: func(z *analyzer, __r *file.Attribute) file.Analysis[attrtype.Type] {
			require.Attribute.Type(z, __r)
			return __r.Type
		},
	},
	Block: struct {
		Required                func(z *analyzer, __r *file.Block) (a file.Analysis[bool])
		Forwarded               func(z *analyzer, __r *file.Block) (a file.AnalysisWithReason[*file.BlockInstance])
		ForwardsAttributes      func(z *analyzer, __r *file.Block) (a file.Analysis[bool])
		CannotForwardAttributes func(z *analyzer, __r *file.Block) (a file.AnalysisWithReason[*file.BlockInstance])
		ElementType             func(z *analyzer, __r *file.Block) (a file.Analysis[elemtype.Type])
		MostRestrictiveElement  func(z *analyzer, __r *file.Block) (a file.AnalysisWithReason[ast.ContainingElement])
	}{
		Required: func(z *analyzer, __r *file.Block) (a file.Analysis[bool]) {
			require.Block.Required(z, __r)
			return __r.Required()
		},
		Forwarded: func(z *analyzer, __r *file.Block) (a file.AnalysisWithReason[*file.BlockInstance]) {
			require.Block.Forwarded(z, __r)
			return __r.Forwarded()
		},
		ForwardsAttributes: func(z *analyzer, __r *file.Block) (a file.Analysis[bool]) {
			require.Block.ForwardsAttributes(z, __r)
			return __r.ForwardsAttributes()
		},
		CannotForwardAttributes: func(z *analyzer, __r *file.Block) (a file.AnalysisWithReason[*file.BlockInstance]) {
			require.Block.CannotForwardAttributes(z, __r)
			return __r.CannotForwardAttributes()
		},
		ElementType: func(z *analyzer, __r *file.Block) (a file.Analysis[elemtype.Type]) {
			require.Block.ElementType(z, __r)
			return __r.ElementType()
		},
		MostRestrictiveElement: func(z *analyzer, __r *file.Block) (a file.AnalysisWithReason[ast.ContainingElement]) {
			require.Block.MostRestrictiveElement(z, __r)
			return __r.MostRestrictiveElement()
		},
	},
	BlockInstance: struct {
		Forwarded               func(z *analyzer, __r *file.BlockInstance) file.Analysis[bool]
		ContainingElements      func(z *analyzer, __r *file.BlockInstance) file.Analysis[file.SliceRef[ast.ContainingElement]]
		ContainingElementSpecs  func(z *analyzer, __r *file.BlockInstance) file.Analysis[file.SliceRef[*file.ElementSpec]]
		CannotForwardAttributes func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.AttributeInhibitor]
		ElementType             func(z *analyzer, __r *file.BlockInstance) (a file.Analysis[elemtype.Type])
		MostRestrictiveElement  func(z *analyzer, __r *file.BlockInstance) (a file.AnalysisWithReason[ast.ContainingElement])
		ForwardsAttributes      func(z *analyzer, __r *file.BlockInstance) (a file.Analysis[bool])
		DefaultOverwritten      func(z *analyzer, __r *file.BlockInstance, cc *file.ComponentCall) bool
		Default                 struct {
			AcceptsAttributes              func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.AndPlaceholderWriter]
			ForwardsReceivedAttributes     func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.AndPlaceholderWriter]
			ElementsWithAndPlaceholder     func(z *analyzer, __r *file.BlockInstance) file.Analysis[file.SliceRef[ast.AttributeReceiver]]
			ElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.BlockInstance) file.Analysis[file.SliceRef[*file.ElementSpec]]
			ForwardsAttributes             func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.AttributeWriter]
			WritesContent                  func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.ContentWriter]
			WritesElements                 func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.ElementWriter]
		}
	}{
		Forwarded: func(z *analyzer, __r *file.BlockInstance) file.Analysis[bool] {
			require.BlockInstance.Forwarded(z, __r)
			return __r.Forwarded
		},
		ContainingElements: func(z *analyzer, __r *file.BlockInstance) file.Analysis[file.SliceRef[ast.ContainingElement]] {
			require.BlockInstance.ContainingElements(z, __r)
			return __r.ContainingElements
		},
		ContainingElementSpecs: func(z *analyzer, __r *file.BlockInstance) file.Analysis[file.SliceRef[*file.ElementSpec]] {
			require.BlockInstance.ContainingElementSpecs(z, __r)
			return __r.ContainingElementSpecs
		},
		CannotForwardAttributes: func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.AttributeInhibitor] {
			require.BlockInstance.CannotForwardAttributes(z, __r)
			return __r.CannotForwardAttributes
		},
		ElementType: func(z *analyzer, __r *file.BlockInstance) (a file.Analysis[elemtype.Type]) {
			require.BlockInstance.ElementType(z, __r)
			return __r.ElementType()
		},
		MostRestrictiveElement: func(z *analyzer, __r *file.BlockInstance) (a file.AnalysisWithReason[ast.ContainingElement]) {
			require.BlockInstance.MostRestrictiveElement(z, __r)
			return __r.MostRestrictiveElement()
		},
		ForwardsAttributes: func(z *analyzer, __r *file.BlockInstance) (a file.Analysis[bool]) {
			require.BlockInstance.ForwardsAttributes(z, __r)
			return __r.ForwardsAttributes()
		},
		DefaultOverwritten: func(z *analyzer, __r *file.BlockInstance, cc *file.ComponentCall) bool {
			require.BlockInstance.DefaultOverwritten(z, __r)
			return __r.DefaultOverwritten(cc)
		},
		Default: struct {
			AcceptsAttributes              func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.AndPlaceholderWriter]
			ForwardsReceivedAttributes     func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.AndPlaceholderWriter]
			ElementsWithAndPlaceholder     func(z *analyzer, __r *file.BlockInstance) file.Analysis[file.SliceRef[ast.AttributeReceiver]]
			ElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.BlockInstance) file.Analysis[file.SliceRef[*file.ElementSpec]]
			ForwardsAttributes             func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.AttributeWriter]
			WritesContent                  func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.ContentWriter]
			WritesElements                 func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.ElementWriter]
		}{
			AcceptsAttributes: func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.AndPlaceholderWriter] {
				require.BlockInstance.Default.AcceptsAttributes(z, __r)
				return __r.Default.AcceptsAttributes
			},
			ForwardsReceivedAttributes: func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.AndPlaceholderWriter] {
				require.BlockInstance.Default.ForwardsReceivedAttributes(z, __r)
				return __r.Default.ForwardsReceivedAttributes
			},
			ElementsWithAndPlaceholder: func(z *analyzer, __r *file.BlockInstance) file.Analysis[file.SliceRef[ast.AttributeReceiver]] {
				require.BlockInstance.Default.ElementsWithAndPlaceholder(z, __r)
				return __r.Default.ElementsWithAndPlaceholder
			},
			ElementSpecsWithAndPlaceholder: func(z *analyzer, __r *file.BlockInstance) file.Analysis[file.SliceRef[*file.ElementSpec]] {
				require.BlockInstance.Default.ElementSpecsWithAndPlaceholder(z, __r)
				return __r.Default.ElementSpecsWithAndPlaceholder
			},
			ForwardsAttributes: func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.AttributeWriter] {
				require.BlockInstance.Default.ForwardsAttributes(z, __r)
				return __r.Default.ForwardsAttributes
			},
			WritesContent: func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.ContentWriter] {
				require.BlockInstance.Default.WritesContent(z, __r)
				return __r.Default.WritesContent
			},
			WritesElements: func(z *analyzer, __r *file.BlockInstance) file.AnalysisWithReason[ast.ElementWriter] {
				require.BlockInstance.Default.WritesElements(z, __r)
				return __r.Default.WritesElements
			},
		},
	},
	BlockSetter: struct {
		WritesAndPlaceholder   func(z *analyzer, __r *file.BlockSetter) (a file.AnalysisWithReason[*file.BlockSetterInstance])
		ForwardsAndPlaceholder func(z *analyzer, __r *file.BlockSetter) (a file.AnalysisWithReason[*file.BlockSetterInstance])
		ForwardsAttributes     func(z *analyzer, __r *file.BlockSetter) (a file.AnalysisWithReason[*file.BlockSetterInstance])
		WritesContent          func(z *analyzer, __r *file.BlockSetter) (a file.AnalysisWithReason[*file.BlockSetterInstance])
		WritesElements         func(z *analyzer, __r *file.BlockSetter) (a file.AnalysisWithReason[*file.BlockSetterInstance])
	}{
		WritesAndPlaceholder: func(z *analyzer, __r *file.BlockSetter) (a file.AnalysisWithReason[*file.BlockSetterInstance]) {
			require.BlockSetter.WritesAndPlaceholder(z, __r)
			return __r.WritesAndPlaceholder()
		},
		ForwardsAndPlaceholder: func(z *analyzer, __r *file.BlockSetter) (a file.AnalysisWithReason[*file.BlockSetterInstance]) {
			require.BlockSetter.ForwardsAndPlaceholder(z, __r)
			return __r.ForwardsAndPlaceholder()
		},
		ForwardsAttributes: func(z *analyzer, __r *file.BlockSetter) (a file.AnalysisWithReason[*file.BlockSetterInstance]) {
			require.BlockSetter.ForwardsAttributes(z, __r)
			return __r.ForwardsAttributes()
		},
		WritesContent: func(z *analyzer, __r *file.BlockSetter) (a file.AnalysisWithReason[*file.BlockSetterInstance]) {
			require.BlockSetter.WritesContent(z, __r)
			return __r.WritesContent()
		},
		WritesElements: func(z *analyzer, __r *file.BlockSetter) (a file.AnalysisWithReason[*file.BlockSetterInstance]) {
			require.BlockSetter.WritesElements(z, __r)
			return __r.WritesElements()
		},
	},
	BlockSetterInstance: struct {
		AcceptsAttributes          func(z *analyzer, __r *file.BlockSetterInstance) file.AnalysisWithReason[ast.AndPlaceholderWriter]
		ForwardsReceivedAttributes func(z *analyzer, __r *file.BlockSetterInstance) file.AnalysisWithReason[ast.AndPlaceholderWriter]
		ForwardsAttributes         func(z *analyzer, __r *file.BlockSetterInstance) file.AnalysisWithReason[ast.AttributeWriter]
		WritesContent              func(z *analyzer, __r *file.BlockSetterInstance) file.AnalysisWithReason[ast.ContentWriter]
		WritesElements             func(z *analyzer, __r *file.BlockSetterInstance) file.AnalysisWithReason[ast.ElementWriter]
	}{
		AcceptsAttributes: func(z *analyzer, __r *file.BlockSetterInstance) file.AnalysisWithReason[ast.AndPlaceholderWriter] {
			require.BlockSetterInstance.AcceptsAttributes(z, __r)
			return __r.AcceptsAttributes
		},
		ForwardsReceivedAttributes: func(z *analyzer, __r *file.BlockSetterInstance) file.AnalysisWithReason[ast.AndPlaceholderWriter] {
			require.BlockSetterInstance.ForwardsReceivedAttributes(z, __r)
			return __r.ForwardsReceivedAttributes
		},
		ForwardsAttributes: func(z *analyzer, __r *file.BlockSetterInstance) file.AnalysisWithReason[ast.AttributeWriter] {
			require.BlockSetterInstance.ForwardsAttributes(z, __r)
			return __r.ForwardsAttributes
		},
		WritesContent: func(z *analyzer, __r *file.BlockSetterInstance) file.AnalysisWithReason[ast.ContentWriter] {
			require.BlockSetterInstance.WritesContent(z, __r)
			return __r.WritesContent
		},
		WritesElements: func(z *analyzer, __r *file.BlockSetterInstance) file.AnalysisWithReason[ast.ElementWriter] {
			require.BlockSetterInstance.WritesElements(z, __r)
			return __r.WritesElements
		},
	},
	Component: struct {
		Circular                                func(z *analyzer, __r *file.Component) bool
		AlwaysAcceptsAttributes                 func(z *analyzer, __r *file.Component) file.AnalysisWithReason[ast.AndPlaceholderWriter]
		AlwaysForwardsReceivedAttributes        func(z *analyzer, __r *file.Component) file.AnalysisWithReason[ast.AndPlaceholderWriter]
		AlwaysForwardsAttributes                func(z *analyzer, __r *file.Component) file.AnalysisWithReason[ast.AttributeWriter]
		AlwaysWritesContent                     func(z *analyzer, __r *file.Component) file.AnalysisWithReason[ast.ContentWriter]
		AlwaysWritesElements                    func(z *analyzer, __r *file.Component) file.AnalysisWithReason[ast.ElementWriter]
		PermanentElementsWithAndPlaceholder     func(z *analyzer, __r *file.Component) file.Analysis[file.SliceRef[ast.AttributeReceiver]]
		PermanentElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.Component) file.Analysis[file.SliceRef[*file.ElementSpec]]
		CouldAcceptAttributes                   func(z *analyzer, __r *file.Component) (a file.AnalysisWithReason[ast.AndPlaceholderWriter])
		CouldForwardReceivedAttributes          func(z *analyzer, __r *file.Component) (a file.AnalysisWithReason[ast.AndPlaceholderWriter])
	}{
		Circular: func(z *analyzer, __r *file.Component) bool {
			require.Component.Circular(z, __r)
			return __r.Circular
		},
		AlwaysAcceptsAttributes: func(z *analyzer, __r *file.Component) file.AnalysisWithReason[ast.AndPlaceholderWriter] {
			require.Component.AlwaysAcceptsAttributes(z, __r)
			return __r.AlwaysAcceptsAttributes
		},
		AlwaysForwardsReceivedAttributes: func(z *analyzer, __r *file.Component) file.AnalysisWithReason[ast.AndPlaceholderWriter] {
			require.Component.AlwaysForwardsReceivedAttributes(z, __r)
			return __r.AlwaysForwardsReceivedAttributes
		},
		AlwaysForwardsAttributes: func(z *analyzer, __r *file.Component) file.AnalysisWithReason[ast.AttributeWriter] {
			require.Component.AlwaysForwardsAttributes(z, __r)
			return __r.AlwaysForwardsAttributes
		},
		AlwaysWritesContent: func(z *analyzer, __r *file.Component) file.AnalysisWithReason[ast.ContentWriter] {
			require.Component.AlwaysWritesContent(z, __r)
			return __r.AlwaysWritesContent
		},
		AlwaysWritesElements: func(z *analyzer, __r *file.Component) file.AnalysisWithReason[ast.ElementWriter] {
			require.Component.AlwaysWritesElements(z, __r)
			return __r.AlwaysWritesElements
		},
		PermanentElementsWithAndPlaceholder: func(z *analyzer, __r *file.Component) file.Analysis[file.SliceRef[ast.AttributeReceiver]] {
			require.Component.PermanentElementsWithAndPlaceholder(z, __r)
			return __r.PermanentElementsWithAndPlaceholder
		},
		PermanentElementSpecsWithAndPlaceholder: func(z *analyzer, __r *file.Component) file.Analysis[file.SliceRef[*file.ElementSpec]] {
			require.Component.PermanentElementSpecsWithAndPlaceholder(z, __r)
			return __r.PermanentElementSpecsWithAndPlaceholder
		},
		CouldAcceptAttributes: func(z *analyzer, __r *file.Component) (a file.AnalysisWithReason[ast.AndPlaceholderWriter]) {
			require.Component.CouldAcceptAttributes(z, __r)
			return __r.CouldAcceptAttributes()
		},
		CouldForwardReceivedAttributes: func(z *analyzer, __r *file.Component) (a file.AnalysisWithReason[ast.AndPlaceholderWriter]) {
			require.Component.CouldForwardReceivedAttributes(z, __r)
			return __r.CouldForwardReceivedAttributes()
		},
	},
	ComponentArgument: struct {
		Value func(z *analyzer, __r *file.ComponentArgument) file.ResolvedValue
	}{
		Value: func(z *analyzer, __r *file.ComponentArgument) file.ResolvedValue {
			require.ComponentArgument.Value(z, __r)
			return __r.Value
		},
	},
	ComponentParameter: struct {
		InferredType  func(z *analyzer, __r *file.ComponentParameter) file.Analysis[file.Type]
		AttributeType func(z *analyzer, __r *file.ComponentParameter) file.Analysis[attrtype.Type]
		AttributeName func(z *analyzer, __r *file.ComponentParameter) file.Analysis[string]
		ResolvedType  func(z *analyzer, __r *file.ComponentParameter) file.Analysis[file.Type]
		Required      func(z *analyzer, __r *file.ComponentParameter) bool
	}{
		InferredType: func(z *analyzer, __r *file.ComponentParameter) file.Analysis[file.Type] {
			require.ComponentParameter.InferredType(z, __r)
			return __r.InferredType
		},
		AttributeType: func(z *analyzer, __r *file.ComponentParameter) file.Analysis[attrtype.Type] {
			require.ComponentParameter.AttributeType(z, __r)
			return __r.AttributeType
		},
		AttributeName: func(z *analyzer, __r *file.ComponentParameter) file.Analysis[string] {
			require.ComponentParameter.AttributeName(z, __r)
			return __r.AttributeName
		},
		ResolvedType: func(z *analyzer, __r *file.ComponentParameter) file.Analysis[file.Type] {
			require.ComponentParameter.ResolvedType(z, __r)
			return __r.ResolvedType()
		},
		Required: func(z *analyzer, __r *file.ComponentParameter) bool {
			require.ComponentParameter.Required(z, __r)
			return __r.Required()
		},
	},
	ComponentCall: struct {
		ReceivesAttributes                func(z *analyzer, __r *file.ComponentCall) file.AnalysisWithReason[ast.AttributeWriter]
		ReceivesAndPlaceholder            func(z *analyzer, __r *file.ComponentCall) file.AnalysisWithReason[ast.AndPlaceholderWriter]
		ElementsWithAndPlaceholder        func(z *analyzer, __r *file.ComponentCall) file.Analysis[file.SliceRef[ast.AttributeReceiver]]
		ElementSpecsWithAndPlaceholder    func(z *analyzer, __r *file.ComponentCall) file.Analysis[file.SliceRef[*file.ElementSpec]]
		AcceptsAttributes                 func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.AndPlaceholderWriter])
		ForwardsAcceptedAttributes        func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.AndPlaceholderWriter])
		ForwardsAndPlaceholder            func(z *analyzer, __r *file.ComponentCall) (a file.Analysis[bool])
		ForwardsReceivedAndPlaceholder    func(z *analyzer, __r *file.ComponentCall) file.AnalysisWithReason[ast.AndPlaceholderWriter]
		BlockSetterForwardsAndPlaceholder func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[*file.BlockSetter])
		ForwardsAttributes                func(z *analyzer, __r *file.ComponentCall) (a file.Analysis[bool])
		ComponentForwardsAttributes       func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.AttributeWriter])
		ForwardsReceivedAttributes        func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.AttributeWriter])
		BlockSetterForwardsAttributes     func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[*file.BlockSetter])
		WritesContent                     func(z *analyzer, __r *file.ComponentCall) (a file.Analysis[bool])
		ComponentWritesContent            func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.ContentWriter])
		BlockSetterWritesContent          func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[*file.BlockSetter])
		WritesElements                    func(z *analyzer, __r *file.ComponentCall) (a file.Analysis[bool])
		ComponentWritesElements           func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.ElementWriter])
		BlockSetterWritesElements         func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[*file.BlockSetter])
	}{
		ReceivesAttributes: func(z *analyzer, __r *file.ComponentCall) file.AnalysisWithReason[ast.AttributeWriter] {
			require.ComponentCall.ReceivesAttributes(z, __r)
			return __r.ReceivesAttributes
		},
		ReceivesAndPlaceholder: func(z *analyzer, __r *file.ComponentCall) file.AnalysisWithReason[ast.AndPlaceholderWriter] {
			require.ComponentCall.ReceivesAndPlaceholder(z, __r)
			return __r.ReceivesAndPlaceholder
		},
		ElementsWithAndPlaceholder: func(z *analyzer, __r *file.ComponentCall) file.Analysis[file.SliceRef[ast.AttributeReceiver]] {
			require.ComponentCall.ElementsWithAndPlaceholder(z, __r)
			return __r.ElementsWithAndPlaceholder
		},
		ElementSpecsWithAndPlaceholder: func(z *analyzer, __r *file.ComponentCall) file.Analysis[file.SliceRef[*file.ElementSpec]] {
			require.ComponentCall.ElementSpecsWithAndPlaceholder(z, __r)
			return __r.ElementSpecsWithAndPlaceholder
		},
		AcceptsAttributes: func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.AndPlaceholderWriter]) {
			require.ComponentCall.AcceptsAttributes(z, __r)
			return __r.AcceptsAttributes()
		},
		ForwardsAcceptedAttributes: func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.AndPlaceholderWriter]) {
			require.ComponentCall.ForwardsAcceptedAttributes(z, __r)
			return __r.ForwardsAcceptedAttributes()
		},
		ForwardsAndPlaceholder: func(z *analyzer, __r *file.ComponentCall) (a file.Analysis[bool]) {
			require.ComponentCall.ForwardsAndPlaceholder(z, __r)
			return __r.ForwardsAndPlaceholder()
		},
		ForwardsReceivedAndPlaceholder: func(z *analyzer, __r *file.ComponentCall) file.AnalysisWithReason[ast.AndPlaceholderWriter] {
			require.ComponentCall.ForwardsReceivedAndPlaceholder(z, __r)
			return __r.ForwardsReceivedAndPlaceholder()
		},
		BlockSetterForwardsAndPlaceholder: func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[*file.BlockSetter]) {
			require.ComponentCall.BlockSetterForwardsAndPlaceholder(z, __r)
			return __r.BlockSetterForwardsAndPlaceholder()
		},
		ForwardsAttributes: func(z *analyzer, __r *file.ComponentCall) (a file.Analysis[bool]) {
			require.ComponentCall.ForwardsAttributes(z, __r)
			return __r.ForwardsAttributes()
		},
		ComponentForwardsAttributes: func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.AttributeWriter]) {
			require.ComponentCall.ComponentForwardsAttributes(z, __r)
			return __r.ComponentForwardsAttributes()
		},
		ForwardsReceivedAttributes: func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.AttributeWriter]) {
			require.ComponentCall.ForwardsReceivedAttributes(z, __r)
			return __r.ForwardsReceivedAttributes()
		},
		BlockSetterForwardsAttributes: func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[*file.BlockSetter]) {
			require.ComponentCall.BlockSetterForwardsAttributes(z, __r)
			return __r.BlockSetterForwardsAttributes()
		},
		WritesContent: func(z *analyzer, __r *file.ComponentCall) (a file.Analysis[bool]) {
			require.ComponentCall.WritesContent(z, __r)
			return __r.WritesContent()
		},
		ComponentWritesContent: func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.ContentWriter]) {
			require.ComponentCall.ComponentWritesContent(z, __r)
			return __r.ComponentWritesContent()
		},
		BlockSetterWritesContent: func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[*file.BlockSetter]) {
			require.ComponentCall.BlockSetterWritesContent(z, __r)
			return __r.BlockSetterWritesContent()
		},
		WritesElements: func(z *analyzer, __r *file.ComponentCall) (a file.Analysis[bool]) {
			require.ComponentCall.WritesElements(z, __r)
			return __r.WritesElements()
		},
		ComponentWritesElements: func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[ast.ElementWriter]) {
			require.ComponentCall.ComponentWritesElements(z, __r)
			return __r.ComponentWritesElements()
		},
		BlockSetterWritesElements: func(z *analyzer, __r *file.ComponentCall) (a file.AnalysisWithReason[*file.BlockSetter]) {
			require.ComponentCall.BlockSetterWritesElements(z, __r)
			return __r.BlockSetterWritesElements()
		},
	},
	ElementSpec: struct {
		Circular func(z *analyzer, __r *file.ElementSpec) bool
		Type     func(z *analyzer, __r *file.ElementSpec) file.Analysis[elemtype.Type]
	}{
		Circular: func(z *analyzer, __r *file.ElementSpec) bool {
			require.ElementSpec.Circular(z, __r)
			return __r.Circular
		},
		Type: func(z *analyzer, __r *file.ElementSpec) file.Analysis[elemtype.Type] {
			require.ElementSpec.Type(z, __r)
			return __r.Type
		},
	},
}

var require struct {
	Attribute struct {
		Value                 func(*analyzer, *file.Attribute)
		Forwarded             func(*analyzer, *file.Attribute)
		Receivers             func(*analyzer, *file.Attribute)
		ReceivingElementSpecs func(*analyzer, *file.Attribute)
		Type                  func(*analyzer, *file.Attribute)
	}
	Block struct {
		Required                func(*analyzer, *file.Block)
		Forwarded               func(*analyzer, *file.Block)
		ForwardsAttributes      func(*analyzer, *file.Block)
		CannotForwardAttributes func(*analyzer, *file.Block)
		ElementType             func(*analyzer, *file.Block)
		MostRestrictiveElement  func(*analyzer, *file.Block)
	}
	BlockInstance struct {
		Forwarded               func(*analyzer, *file.BlockInstance)
		ContainingElements      func(*analyzer, *file.BlockInstance)
		ContainingElementSpecs  func(*analyzer, *file.BlockInstance)
		CannotForwardAttributes func(*analyzer, *file.BlockInstance)
		ElementType             func(*analyzer, *file.BlockInstance)
		MostRestrictiveElement  func(*analyzer, *file.BlockInstance)
		ForwardsAttributes      func(*analyzer, *file.BlockInstance)
		DefaultOverwritten      func(*analyzer, *file.BlockInstance)
		Default                 struct {
			AcceptsAttributes              func(*analyzer, *file.BlockInstance)
			ForwardsReceivedAttributes     func(*analyzer, *file.BlockInstance)
			ElementsWithAndPlaceholder     func(*analyzer, *file.BlockInstance)
			ElementSpecsWithAndPlaceholder func(*analyzer, *file.BlockInstance)
			ForwardsAttributes             func(*analyzer, *file.BlockInstance)
			WritesContent                  func(*analyzer, *file.BlockInstance)
			WritesElements                 func(*analyzer, *file.BlockInstance)
		}
	}
	BlockSetter struct {
		WritesAndPlaceholder   func(*analyzer, *file.BlockSetter)
		ForwardsAndPlaceholder func(*analyzer, *file.BlockSetter)
		ForwardsAttributes     func(*analyzer, *file.BlockSetter)
		WritesContent          func(*analyzer, *file.BlockSetter)
		WritesElements         func(*analyzer, *file.BlockSetter)
	}
	BlockSetterInstance struct {
		AcceptsAttributes          func(*analyzer, *file.BlockSetterInstance)
		ForwardsReceivedAttributes func(*analyzer, *file.BlockSetterInstance)
		ForwardsAttributes         func(*analyzer, *file.BlockSetterInstance)
		WritesContent              func(*analyzer, *file.BlockSetterInstance)
		WritesElements             func(*analyzer, *file.BlockSetterInstance)
	}
	Component struct {
		Circular                                func(*analyzer, *file.Component)
		AlwaysAcceptsAttributes                 func(*analyzer, *file.Component)
		AlwaysForwardsReceivedAttributes        func(*analyzer, *file.Component)
		AlwaysForwardsAttributes                func(*analyzer, *file.Component)
		AlwaysWritesContent                     func(*analyzer, *file.Component)
		AlwaysWritesElements                    func(*analyzer, *file.Component)
		PermanentElementsWithAndPlaceholder     func(*analyzer, *file.Component)
		PermanentElementSpecsWithAndPlaceholder func(*analyzer, *file.Component)
		CouldAcceptAttributes                   func(*analyzer, *file.Component)
		CouldForwardReceivedAttributes          func(*analyzer, *file.Component)
	}
	ComponentArgument struct {
		Value func(*analyzer, *file.ComponentArgument)
	}
	ComponentParameter struct {
		InferredType  func(*analyzer, *file.ComponentParameter)
		AttributeType func(*analyzer, *file.ComponentParameter)
		AttributeName func(*analyzer, *file.ComponentParameter)
		ResolvedType  func(*analyzer, *file.ComponentParameter)
		Required      func(*analyzer, *file.ComponentParameter)
	}
	ComponentCall struct {
		ReceivesAttributes                func(*analyzer, *file.ComponentCall)
		ReceivesAndPlaceholder            func(*analyzer, *file.ComponentCall)
		ElementsWithAndPlaceholder        func(*analyzer, *file.ComponentCall)
		ElementSpecsWithAndPlaceholder    func(*analyzer, *file.ComponentCall)
		AcceptsAttributes                 func(*analyzer, *file.ComponentCall)
		ForwardsAcceptedAttributes        func(*analyzer, *file.ComponentCall)
		ForwardsAndPlaceholder            func(*analyzer, *file.ComponentCall)
		ForwardsReceivedAndPlaceholder    func(*analyzer, *file.ComponentCall)
		BlockSetterForwardsAndPlaceholder func(*analyzer, *file.ComponentCall)
		ForwardsAttributes                func(*analyzer, *file.ComponentCall)
		ComponentForwardsAttributes       func(*analyzer, *file.ComponentCall)
		ForwardsReceivedAttributes        func(*analyzer, *file.ComponentCall)
		BlockSetterForwardsAttributes     func(*analyzer, *file.ComponentCall)
		WritesContent                     func(*analyzer, *file.ComponentCall)
		ComponentWritesContent            func(*analyzer, *file.ComponentCall)
		BlockSetterWritesContent          func(*analyzer, *file.ComponentCall)
		WritesElements                    func(*analyzer, *file.ComponentCall)
		ComponentWritesElements           func(*analyzer, *file.ComponentCall)
		BlockSetterWritesElements         func(*analyzer, *file.ComponentCall)
	}
	ElementSpec struct {
		Circular func(*analyzer, *file.ElementSpec)
		Type     func(*analyzer, *file.ElementSpec)
	}
}

func init() {
	require = struct {
		Attribute struct {
			Value                 func(*analyzer, *file.Attribute)
			Forwarded             func(*analyzer, *file.Attribute)
			Receivers             func(*analyzer, *file.Attribute)
			ReceivingElementSpecs func(*analyzer, *file.Attribute)
			Type                  func(*analyzer, *file.Attribute)
		}
		Block struct {
			Required                func(*analyzer, *file.Block)
			Forwarded               func(*analyzer, *file.Block)
			ForwardsAttributes      func(*analyzer, *file.Block)
			CannotForwardAttributes func(*analyzer, *file.Block)
			ElementType             func(*analyzer, *file.Block)
			MostRestrictiveElement  func(*analyzer, *file.Block)
		}
		BlockInstance struct {
			Forwarded               func(*analyzer, *file.BlockInstance)
			ContainingElements      func(*analyzer, *file.BlockInstance)
			ContainingElementSpecs  func(*analyzer, *file.BlockInstance)
			CannotForwardAttributes func(*analyzer, *file.BlockInstance)
			ElementType             func(*analyzer, *file.BlockInstance)
			MostRestrictiveElement  func(*analyzer, *file.BlockInstance)
			ForwardsAttributes      func(*analyzer, *file.BlockInstance)
			DefaultOverwritten      func(*analyzer, *file.BlockInstance)
			Default                 struct {
				AcceptsAttributes              func(*analyzer, *file.BlockInstance)
				ForwardsReceivedAttributes     func(*analyzer, *file.BlockInstance)
				ElementsWithAndPlaceholder     func(*analyzer, *file.BlockInstance)
				ElementSpecsWithAndPlaceholder func(*analyzer, *file.BlockInstance)
				ForwardsAttributes             func(*analyzer, *file.BlockInstance)
				WritesContent                  func(*analyzer, *file.BlockInstance)
				WritesElements                 func(*analyzer, *file.BlockInstance)
			}
		}
		BlockSetter struct {
			WritesAndPlaceholder   func(*analyzer, *file.BlockSetter)
			ForwardsAndPlaceholder func(*analyzer, *file.BlockSetter)
			ForwardsAttributes     func(*analyzer, *file.BlockSetter)
			WritesContent          func(*analyzer, *file.BlockSetter)
			WritesElements         func(*analyzer, *file.BlockSetter)
		}
		BlockSetterInstance struct {
			AcceptsAttributes          func(*analyzer, *file.BlockSetterInstance)
			ForwardsReceivedAttributes func(*analyzer, *file.BlockSetterInstance)
			ForwardsAttributes         func(*analyzer, *file.BlockSetterInstance)
			WritesContent              func(*analyzer, *file.BlockSetterInstance)
			WritesElements             func(*analyzer, *file.BlockSetterInstance)
		}
		Component struct {
			Circular                                func(*analyzer, *file.Component)
			AlwaysAcceptsAttributes                 func(*analyzer, *file.Component)
			AlwaysForwardsReceivedAttributes        func(*analyzer, *file.Component)
			AlwaysForwardsAttributes                func(*analyzer, *file.Component)
			AlwaysWritesContent                     func(*analyzer, *file.Component)
			AlwaysWritesElements                    func(*analyzer, *file.Component)
			PermanentElementsWithAndPlaceholder     func(*analyzer, *file.Component)
			PermanentElementSpecsWithAndPlaceholder func(*analyzer, *file.Component)
			CouldAcceptAttributes                   func(*analyzer, *file.Component)
			CouldForwardReceivedAttributes          func(*analyzer, *file.Component)
		}
		ComponentArgument struct {
			Value func(*analyzer, *file.ComponentArgument)
		}
		ComponentParameter struct {
			InferredType  func(*analyzer, *file.ComponentParameter)
			AttributeType func(*analyzer, *file.ComponentParameter)
			AttributeName func(*analyzer, *file.ComponentParameter)
			ResolvedType  func(*analyzer, *file.ComponentParameter)
			Required      func(*analyzer, *file.ComponentParameter)
		}
		ComponentCall struct {
			ReceivesAttributes                func(*analyzer, *file.ComponentCall)
			ReceivesAndPlaceholder            func(*analyzer, *file.ComponentCall)
			ElementsWithAndPlaceholder        func(*analyzer, *file.ComponentCall)
			ElementSpecsWithAndPlaceholder    func(*analyzer, *file.ComponentCall)
			AcceptsAttributes                 func(*analyzer, *file.ComponentCall)
			ForwardsAcceptedAttributes        func(*analyzer, *file.ComponentCall)
			ForwardsAndPlaceholder            func(*analyzer, *file.ComponentCall)
			ForwardsReceivedAndPlaceholder    func(*analyzer, *file.ComponentCall)
			BlockSetterForwardsAndPlaceholder func(*analyzer, *file.ComponentCall)
			ForwardsAttributes                func(*analyzer, *file.ComponentCall)
			ComponentForwardsAttributes       func(*analyzer, *file.ComponentCall)
			ForwardsReceivedAttributes        func(*analyzer, *file.ComponentCall)
			BlockSetterForwardsAttributes     func(*analyzer, *file.ComponentCall)
			WritesContent                     func(*analyzer, *file.ComponentCall)
			ComponentWritesContent            func(*analyzer, *file.ComponentCall)
			BlockSetterWritesContent          func(*analyzer, *file.ComponentCall)
			WritesElements                    func(*analyzer, *file.ComponentCall)
			ComponentWritesElements           func(*analyzer, *file.ComponentCall)
			BlockSetterWritesElements         func(*analyzer, *file.ComponentCall)
		}
		ElementSpec struct {
			Circular func(*analyzer, *file.ElementSpec)
			Type     func(*analyzer, *file.ElementSpec)
		}
	}{
		Attribute: struct {
			Value                 func(*analyzer, *file.Attribute)
			Forwarded             func(*analyzer, *file.Attribute)
			Receivers             func(*analyzer, *file.Attribute)
			ReceivingElementSpecs func(*analyzer, *file.Attribute)
			Type                  func(*analyzer, *file.Attribute)
		}{
			Value:                 requirer{}.Attribute_Value,
			Forwarded:             requirer{}.Attribute_Forwarded,
			Receivers:             requirer{}.Attribute_Receivers,
			ReceivingElementSpecs: requirer{}.Attribute_ReceivingElementSpecs,
			Type:                  requirer{}.Attribute_Type,
		},
		Block: struct {
			Required                func(*analyzer, *file.Block)
			Forwarded               func(*analyzer, *file.Block)
			ForwardsAttributes      func(*analyzer, *file.Block)
			CannotForwardAttributes func(*analyzer, *file.Block)
			ElementType             func(*analyzer, *file.Block)
			MostRestrictiveElement  func(*analyzer, *file.Block)
		}{
			Required:                requirer{}.Block_Required,
			Forwarded:               requirer{}.Block_Forwarded,
			ForwardsAttributes:      requirer{}.Block_ForwardsAttributes,
			CannotForwardAttributes: requirer{}.Block_CannotForwardAttributes,
			ElementType:             requirer{}.Block_ElementType,
			MostRestrictiveElement:  requirer{}.Block_MostRestrictiveElement,
		},
		BlockInstance: struct {
			Forwarded               func(*analyzer, *file.BlockInstance)
			ContainingElements      func(*analyzer, *file.BlockInstance)
			ContainingElementSpecs  func(*analyzer, *file.BlockInstance)
			CannotForwardAttributes func(*analyzer, *file.BlockInstance)
			ElementType             func(*analyzer, *file.BlockInstance)
			MostRestrictiveElement  func(*analyzer, *file.BlockInstance)
			ForwardsAttributes      func(*analyzer, *file.BlockInstance)
			DefaultOverwritten      func(*analyzer, *file.BlockInstance)
			Default                 struct {
				AcceptsAttributes              func(*analyzer, *file.BlockInstance)
				ForwardsReceivedAttributes     func(*analyzer, *file.BlockInstance)
				ElementsWithAndPlaceholder     func(*analyzer, *file.BlockInstance)
				ElementSpecsWithAndPlaceholder func(*analyzer, *file.BlockInstance)
				ForwardsAttributes             func(*analyzer, *file.BlockInstance)
				WritesContent                  func(*analyzer, *file.BlockInstance)
				WritesElements                 func(*analyzer, *file.BlockInstance)
			}
		}{
			Forwarded:               requirer{}.BlockInstance_Forwarded,
			ContainingElements:      requirer{}.BlockInstance_ContainingElements,
			ContainingElementSpecs:  requirer{}.BlockInstance_ContainingElementSpecs,
			CannotForwardAttributes: requirer{}.BlockInstance_CannotForwardAttributes,
			ElementType:             requirer{}.BlockInstance_ElementType,
			MostRestrictiveElement:  requirer{}.BlockInstance_MostRestrictiveElement,
			ForwardsAttributes:      requirer{}.BlockInstance_ForwardsAttributes,
			DefaultOverwritten:      requirer{}.BlockInstance_DefaultOverwritten,
			Default: struct {
				AcceptsAttributes              func(*analyzer, *file.BlockInstance)
				ForwardsReceivedAttributes     func(*analyzer, *file.BlockInstance)
				ElementsWithAndPlaceholder     func(*analyzer, *file.BlockInstance)
				ElementSpecsWithAndPlaceholder func(*analyzer, *file.BlockInstance)
				ForwardsAttributes             func(*analyzer, *file.BlockInstance)
				WritesContent                  func(*analyzer, *file.BlockInstance)
				WritesElements                 func(*analyzer, *file.BlockInstance)
			}{
				AcceptsAttributes:              requirer{}.BlockInstance_Default_AcceptsAttributes,
				ForwardsReceivedAttributes:     requirer{}.BlockInstance_Default_ForwardsReceivedAttributes,
				ElementsWithAndPlaceholder:     requirer{}.BlockInstance_Default_ElementsWithAndPlaceholder,
				ElementSpecsWithAndPlaceholder: requirer{}.BlockInstance_Default_ElementSpecsWithAndPlaceholder,
				ForwardsAttributes:             requirer{}.BlockInstance_Default_ForwardsAttributes,
				WritesContent:                  requirer{}.BlockInstance_Default_WritesContent,
				WritesElements:                 requirer{}.BlockInstance_Default_WritesElements,
			},
		},
		BlockSetter: struct {
			WritesAndPlaceholder   func(*analyzer, *file.BlockSetter)
			ForwardsAndPlaceholder func(*analyzer, *file.BlockSetter)
			ForwardsAttributes     func(*analyzer, *file.BlockSetter)
			WritesContent          func(*analyzer, *file.BlockSetter)
			WritesElements         func(*analyzer, *file.BlockSetter)
		}{
			WritesAndPlaceholder:   requirer{}.BlockSetter_WritesAndPlaceholder,
			ForwardsAndPlaceholder: requirer{}.BlockSetter_ForwardsAndPlaceholder,
			ForwardsAttributes:     requirer{}.BlockSetter_ForwardsAttributes,
			WritesContent:          requirer{}.BlockSetter_WritesContent,
			WritesElements:         requirer{}.BlockSetter_WritesElements,
		},
		BlockSetterInstance: struct {
			AcceptsAttributes          func(*analyzer, *file.BlockSetterInstance)
			ForwardsReceivedAttributes func(*analyzer, *file.BlockSetterInstance)
			ForwardsAttributes         func(*analyzer, *file.BlockSetterInstance)
			WritesContent              func(*analyzer, *file.BlockSetterInstance)
			WritesElements             func(*analyzer, *file.BlockSetterInstance)
		}{
			AcceptsAttributes:          requirer{}.BlockSetterInstance_AcceptsAttributes,
			ForwardsReceivedAttributes: requirer{}.BlockSetterInstance_ForwardsReceivedAttributes,
			ForwardsAttributes:         requirer{}.BlockSetterInstance_ForwardsAttributes,
			WritesContent:              requirer{}.BlockSetterInstance_WritesContent,
			WritesElements:             requirer{}.BlockSetterInstance_WritesElements,
		},
		Component: struct {
			Circular                                func(*analyzer, *file.Component)
			AlwaysAcceptsAttributes                 func(*analyzer, *file.Component)
			AlwaysForwardsReceivedAttributes        func(*analyzer, *file.Component)
			AlwaysForwardsAttributes                func(*analyzer, *file.Component)
			AlwaysWritesContent                     func(*analyzer, *file.Component)
			AlwaysWritesElements                    func(*analyzer, *file.Component)
			PermanentElementsWithAndPlaceholder     func(*analyzer, *file.Component)
			PermanentElementSpecsWithAndPlaceholder func(*analyzer, *file.Component)
			CouldAcceptAttributes                   func(*analyzer, *file.Component)
			CouldForwardReceivedAttributes          func(*analyzer, *file.Component)
		}{
			Circular:                                requirer{}.Component_Circular,
			AlwaysAcceptsAttributes:                 requirer{}.Component_AlwaysAcceptsAttributes,
			AlwaysForwardsReceivedAttributes:        requirer{}.Component_AlwaysForwardsReceivedAttributes,
			AlwaysForwardsAttributes:                requirer{}.Component_AlwaysForwardsAttributes,
			AlwaysWritesContent:                     requirer{}.Component_AlwaysWritesContent,
			AlwaysWritesElements:                    requirer{}.Component_AlwaysWritesElements,
			PermanentElementsWithAndPlaceholder:     requirer{}.Component_PermanentElementsWithAndPlaceholder,
			PermanentElementSpecsWithAndPlaceholder: requirer{}.Component_PermanentElementSpecsWithAndPlaceholder,
			CouldAcceptAttributes:                   requirer{}.Component_CouldAcceptAttributes,
			CouldForwardReceivedAttributes:          requirer{}.Component_CouldForwardReceivedAttributes,
		},
		ComponentArgument: struct {
			Value func(*analyzer, *file.ComponentArgument)
		}{
			Value: requirer{}.ComponentArgument_Value,
		},
		ComponentParameter: struct {
			InferredType  func(*analyzer, *file.ComponentParameter)
			AttributeType func(*analyzer, *file.ComponentParameter)
			AttributeName func(*analyzer, *file.ComponentParameter)
			ResolvedType  func(*analyzer, *file.ComponentParameter)
			Required      func(*analyzer, *file.ComponentParameter)
		}{
			InferredType:  requirer{}.ComponentParameter_InferredType,
			AttributeType: requirer{}.ComponentParameter_AttributeType,
			AttributeName: requirer{}.ComponentParameter_AttributeName,
			ResolvedType:  requirer{}.ComponentParameter_ResolvedType,
			Required:      requirer{}.ComponentParameter_Required,
		},
		ComponentCall: struct {
			ReceivesAttributes                func(*analyzer, *file.ComponentCall)
			ReceivesAndPlaceholder            func(*analyzer, *file.ComponentCall)
			ElementsWithAndPlaceholder        func(*analyzer, *file.ComponentCall)
			ElementSpecsWithAndPlaceholder    func(*analyzer, *file.ComponentCall)
			AcceptsAttributes                 func(*analyzer, *file.ComponentCall)
			ForwardsAcceptedAttributes        func(*analyzer, *file.ComponentCall)
			ForwardsAndPlaceholder            func(*analyzer, *file.ComponentCall)
			ForwardsReceivedAndPlaceholder    func(*analyzer, *file.ComponentCall)
			BlockSetterForwardsAndPlaceholder func(*analyzer, *file.ComponentCall)
			ForwardsAttributes                func(*analyzer, *file.ComponentCall)
			ComponentForwardsAttributes       func(*analyzer, *file.ComponentCall)
			ForwardsReceivedAttributes        func(*analyzer, *file.ComponentCall)
			BlockSetterForwardsAttributes     func(*analyzer, *file.ComponentCall)
			WritesContent                     func(*analyzer, *file.ComponentCall)
			ComponentWritesContent            func(*analyzer, *file.ComponentCall)
			BlockSetterWritesContent          func(*analyzer, *file.ComponentCall)
			WritesElements                    func(*analyzer, *file.ComponentCall)
			ComponentWritesElements           func(*analyzer, *file.ComponentCall)
			BlockSetterWritesElements         func(*analyzer, *file.ComponentCall)
		}{
			ReceivesAttributes:                requirer{}.ComponentCall_ReceivesAttributes,
			ReceivesAndPlaceholder:            requirer{}.ComponentCall_ReceivesAndPlaceholder,
			ElementsWithAndPlaceholder:        requirer{}.ComponentCall_ElementsWithAndPlaceholder,
			ElementSpecsWithAndPlaceholder:    requirer{}.ComponentCall_ElementSpecsWithAndPlaceholder,
			AcceptsAttributes:                 requirer{}.ComponentCall_AcceptsAttributes,
			ForwardsAcceptedAttributes:        requirer{}.ComponentCall_ForwardsAcceptedAttributes,
			ForwardsAndPlaceholder:            requirer{}.ComponentCall_ForwardsAndPlaceholder,
			ForwardsReceivedAndPlaceholder:    requirer{}.ComponentCall_ForwardsReceivedAndPlaceholder,
			BlockSetterForwardsAndPlaceholder: requirer{}.ComponentCall_BlockSetterForwardsAndPlaceholder,
			ForwardsAttributes:                requirer{}.ComponentCall_ForwardsAttributes,
			ComponentForwardsAttributes:       requirer{}.ComponentCall_ComponentForwardsAttributes,
			ForwardsReceivedAttributes:        requirer{}.ComponentCall_ForwardsReceivedAttributes,
			BlockSetterForwardsAttributes:     requirer{}.ComponentCall_BlockSetterForwardsAttributes,
			WritesContent:                     requirer{}.ComponentCall_WritesContent,
			ComponentWritesContent:            requirer{}.ComponentCall_ComponentWritesContent,
			BlockSetterWritesContent:          requirer{}.ComponentCall_BlockSetterWritesContent,
			WritesElements:                    requirer{}.ComponentCall_WritesElements,
			ComponentWritesElements:           requirer{}.ComponentCall_ComponentWritesElements,
			BlockSetterWritesElements:         requirer{}.ComponentCall_BlockSetterWritesElements,
		},
		ElementSpec: struct {
			Circular func(*analyzer, *file.ElementSpec)
			Type     func(*analyzer, *file.ElementSpec)
		}{
			Circular: requirer{}.ElementSpec_Circular,
			Type:     requirer{}.ElementSpec_Type,
		},
	}
}

type analyzedFileSymbol string

var analyzed = struct {
	Attribute struct {
		Value                 func(z *analyzer, __r *file.Attribute)
		Forwarded             func(z *analyzer, __r *file.Attribute)
		Receivers             func(z *analyzer, __r *file.Attribute)
		ReceivingElementSpecs func(z *analyzer, __r *file.Attribute)
		Type                  func(z *analyzer, __r *file.Attribute)
	}
	Block struct {
	}
	BlockInstance struct {
		Forwarded               func(z *analyzer, __r *file.BlockInstance)
		ContainingElements      func(z *analyzer, __r *file.BlockInstance)
		ContainingElementSpecs  func(z *analyzer, __r *file.BlockInstance)
		CannotForwardAttributes func(z *analyzer, __r *file.BlockInstance)
		Default                 struct {
			AcceptsAttributes              func(z *analyzer, __r *file.BlockInstance)
			ForwardsReceivedAttributes     func(z *analyzer, __r *file.BlockInstance)
			ElementsWithAndPlaceholder     func(z *analyzer, __r *file.BlockInstance)
			ElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.BlockInstance)
			ForwardsAttributes             func(z *analyzer, __r *file.BlockInstance)
			WritesContent                  func(z *analyzer, __r *file.BlockInstance)
			WritesElements                 func(z *analyzer, __r *file.BlockInstance)
		}
	}
	BlockSetter struct {
	}
	BlockSetterInstance struct {
		AcceptsAttributes          func(z *analyzer, __r *file.BlockSetterInstance)
		ForwardsReceivedAttributes func(z *analyzer, __r *file.BlockSetterInstance)
		ForwardsAttributes         func(z *analyzer, __r *file.BlockSetterInstance)
		WritesContent              func(z *analyzer, __r *file.BlockSetterInstance)
		WritesElements             func(z *analyzer, __r *file.BlockSetterInstance)
	}
	Component struct {
		Circular                                func(z *analyzer, __r *file.Component)
		AlwaysAcceptsAttributes                 func(z *analyzer, __r *file.Component)
		AlwaysForwardsReceivedAttributes        func(z *analyzer, __r *file.Component)
		AlwaysForwardsAttributes                func(z *analyzer, __r *file.Component)
		AlwaysWritesContent                     func(z *analyzer, __r *file.Component)
		AlwaysWritesElements                    func(z *analyzer, __r *file.Component)
		PermanentElementsWithAndPlaceholder     func(z *analyzer, __r *file.Component)
		PermanentElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.Component)
	}
	ComponentArgument struct {
		Value func(z *analyzer, __r *file.ComponentArgument)
	}
	ComponentParameter struct {
		InferredType  func(z *analyzer, __r *file.ComponentParameter)
		AttributeType func(z *analyzer, __r *file.ComponentParameter)
		AttributeName func(z *analyzer, __r *file.ComponentParameter)
	}
	ComponentCall struct {
		ReceivesAttributes             func(z *analyzer, __r *file.ComponentCall)
		ReceivesAndPlaceholder         func(z *analyzer, __r *file.ComponentCall)
		ElementsWithAndPlaceholder     func(z *analyzer, __r *file.ComponentCall)
		ElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.ComponentCall)
	}
	ElementSpec struct {
		Circular func(z *analyzer, __r *file.ElementSpec)
		Type     func(z *analyzer, __r *file.ElementSpec)
	}
}{
	Attribute: struct {
		Value                 func(z *analyzer, __r *file.Attribute)
		Forwarded             func(z *analyzer, __r *file.Attribute)
		Receivers             func(z *analyzer, __r *file.Attribute)
		ReceivingElementSpecs func(z *analyzer, __r *file.Attribute)
		Type                  func(z *analyzer, __r *file.Attribute)
	}{
		Value: func(z *analyzer, __r *file.Attribute) {
			z.Ran(__r, analyzedFileSymbol("Attribute.Value"))
		},
		Forwarded: func(z *analyzer, __r *file.Attribute) {
			z.Ran(__r, analyzedFileSymbol("Attribute.Forwarded"))
		},
		Receivers: func(z *analyzer, __r *file.Attribute) {
			z.Ran(__r, analyzedFileSymbol("Attribute.Receivers"))
		},
		ReceivingElementSpecs: func(z *analyzer, __r *file.Attribute) {
			z.Ran(__r, analyzedFileSymbol("Attribute.ReceivingElementSpecs"))
		},
		Type: func(z *analyzer, __r *file.Attribute) {
			z.Ran(__r, analyzedFileSymbol("Attribute.Type"))
		},
	},
	Block: struct {
	}{},
	BlockInstance: struct {
		Forwarded               func(z *analyzer, __r *file.BlockInstance)
		ContainingElements      func(z *analyzer, __r *file.BlockInstance)
		ContainingElementSpecs  func(z *analyzer, __r *file.BlockInstance)
		CannotForwardAttributes func(z *analyzer, __r *file.BlockInstance)
		Default                 struct {
			AcceptsAttributes              func(z *analyzer, __r *file.BlockInstance)
			ForwardsReceivedAttributes     func(z *analyzer, __r *file.BlockInstance)
			ElementsWithAndPlaceholder     func(z *analyzer, __r *file.BlockInstance)
			ElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.BlockInstance)
			ForwardsAttributes             func(z *analyzer, __r *file.BlockInstance)
			WritesContent                  func(z *analyzer, __r *file.BlockInstance)
			WritesElements                 func(z *analyzer, __r *file.BlockInstance)
		}
	}{
		Forwarded: func(z *analyzer, __r *file.BlockInstance) {
			z.Ran(__r, analyzedFileSymbol("BlockInstance.Forwarded"))
		},
		ContainingElements: func(z *analyzer, __r *file.BlockInstance) {
			z.Ran(__r, analyzedFileSymbol("BlockInstance.ContainingElements"))
		},
		ContainingElementSpecs: func(z *analyzer, __r *file.BlockInstance) {
			z.Ran(__r, analyzedFileSymbol("BlockInstance.ContainingElementSpecs"))
		},
		CannotForwardAttributes: func(z *analyzer, __r *file.BlockInstance) {
			z.Ran(__r, analyzedFileSymbol("BlockInstance.CannotForwardAttributes"))
		},
		Default: struct {
			AcceptsAttributes              func(z *analyzer, __r *file.BlockInstance)
			ForwardsReceivedAttributes     func(z *analyzer, __r *file.BlockInstance)
			ElementsWithAndPlaceholder     func(z *analyzer, __r *file.BlockInstance)
			ElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.BlockInstance)
			ForwardsAttributes             func(z *analyzer, __r *file.BlockInstance)
			WritesContent                  func(z *analyzer, __r *file.BlockInstance)
			WritesElements                 func(z *analyzer, __r *file.BlockInstance)
		}{
			AcceptsAttributes: func(z *analyzer, __r *file.BlockInstance) {
				z.Ran(__r, analyzedFileSymbol("BlockInstance.Default.AcceptsAttributes"))
			},
			ForwardsReceivedAttributes: func(z *analyzer, __r *file.BlockInstance) {
				z.Ran(__r, analyzedFileSymbol("BlockInstance.Default.ForwardsReceivedAttributes"))
			},
			ElementsWithAndPlaceholder: func(z *analyzer, __r *file.BlockInstance) {
				z.Ran(__r, analyzedFileSymbol("BlockInstance.Default.ElementsWithAndPlaceholder"))
			},
			ElementSpecsWithAndPlaceholder: func(z *analyzer, __r *file.BlockInstance) {
				z.Ran(__r, analyzedFileSymbol("BlockInstance.Default.ElementSpecsWithAndPlaceholder"))
			},
			ForwardsAttributes: func(z *analyzer, __r *file.BlockInstance) {
				z.Ran(__r, analyzedFileSymbol("BlockInstance.Default.ForwardsAttributes"))
			},
			WritesContent: func(z *analyzer, __r *file.BlockInstance) {
				z.Ran(__r, analyzedFileSymbol("BlockInstance.Default.WritesContent"))
			},
			WritesElements: func(z *analyzer, __r *file.BlockInstance) {
				z.Ran(__r, analyzedFileSymbol("BlockInstance.Default.WritesElements"))
			},
		},
	},
	BlockSetter: struct {
	}{},
	BlockSetterInstance: struct {
		AcceptsAttributes          func(z *analyzer, __r *file.BlockSetterInstance)
		ForwardsReceivedAttributes func(z *analyzer, __r *file.BlockSetterInstance)
		ForwardsAttributes         func(z *analyzer, __r *file.BlockSetterInstance)
		WritesContent              func(z *analyzer, __r *file.BlockSetterInstance)
		WritesElements             func(z *analyzer, __r *file.BlockSetterInstance)
	}{
		AcceptsAttributes: func(z *analyzer, __r *file.BlockSetterInstance) {
			z.Ran(__r, analyzedFileSymbol("BlockSetterInstance.AcceptsAttributes"))
		},
		ForwardsReceivedAttributes: func(z *analyzer, __r *file.BlockSetterInstance) {
			z.Ran(__r, analyzedFileSymbol("BlockSetterInstance.ForwardsReceivedAttributes"))
		},
		ForwardsAttributes: func(z *analyzer, __r *file.BlockSetterInstance) {
			z.Ran(__r, analyzedFileSymbol("BlockSetterInstance.ForwardsAttributes"))
		},
		WritesContent: func(z *analyzer, __r *file.BlockSetterInstance) {
			z.Ran(__r, analyzedFileSymbol("BlockSetterInstance.WritesContent"))
		},
		WritesElements: func(z *analyzer, __r *file.BlockSetterInstance) {
			z.Ran(__r, analyzedFileSymbol("BlockSetterInstance.WritesElements"))
		},
	},
	Component: struct {
		Circular                                func(z *analyzer, __r *file.Component)
		AlwaysAcceptsAttributes                 func(z *analyzer, __r *file.Component)
		AlwaysForwardsReceivedAttributes        func(z *analyzer, __r *file.Component)
		AlwaysForwardsAttributes                func(z *analyzer, __r *file.Component)
		AlwaysWritesContent                     func(z *analyzer, __r *file.Component)
		AlwaysWritesElements                    func(z *analyzer, __r *file.Component)
		PermanentElementsWithAndPlaceholder     func(z *analyzer, __r *file.Component)
		PermanentElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.Component)
	}{
		Circular: func(z *analyzer, __r *file.Component) {
			z.Ran(__r, analyzedFileSymbol("Component.Circular"))
		},
		AlwaysAcceptsAttributes: func(z *analyzer, __r *file.Component) {
			z.Ran(__r, analyzedFileSymbol("Component.AlwaysAcceptsAttributes"))
		},
		AlwaysForwardsReceivedAttributes: func(z *analyzer, __r *file.Component) {
			z.Ran(__r, analyzedFileSymbol("Component.AlwaysForwardsReceivedAttributes"))
		},
		AlwaysForwardsAttributes: func(z *analyzer, __r *file.Component) {
			z.Ran(__r, analyzedFileSymbol("Component.AlwaysForwardsAttributes"))
		},
		AlwaysWritesContent: func(z *analyzer, __r *file.Component) {
			z.Ran(__r, analyzedFileSymbol("Component.AlwaysWritesContent"))
		},
		AlwaysWritesElements: func(z *analyzer, __r *file.Component) {
			z.Ran(__r, analyzedFileSymbol("Component.AlwaysWritesElements"))
		},
		PermanentElementsWithAndPlaceholder: func(z *analyzer, __r *file.Component) {
			z.Ran(__r, analyzedFileSymbol("Component.PermanentElementsWithAndPlaceholder"))
		},
		PermanentElementSpecsWithAndPlaceholder: func(z *analyzer, __r *file.Component) {
			z.Ran(__r, analyzedFileSymbol("Component.PermanentElementSpecsWithAndPlaceholder"))
		},
	},
	ComponentArgument: struct {
		Value func(z *analyzer, __r *file.ComponentArgument)
	}{
		Value: func(z *analyzer, __r *file.ComponentArgument) {
			z.Ran(__r, analyzedFileSymbol("ComponentArgument.Value"))
		},
	},
	ComponentParameter: struct {
		InferredType  func(z *analyzer, __r *file.ComponentParameter)
		AttributeType func(z *analyzer, __r *file.ComponentParameter)
		AttributeName func(z *analyzer, __r *file.ComponentParameter)
	}{
		InferredType: func(z *analyzer, __r *file.ComponentParameter) {
			z.Ran(__r, analyzedFileSymbol("ComponentParameter.InferredType"))
		},
		AttributeType: func(z *analyzer, __r *file.ComponentParameter) {
			z.Ran(__r, analyzedFileSymbol("ComponentParameter.AttributeType"))
		},
		AttributeName: func(z *analyzer, __r *file.ComponentParameter) {
			z.Ran(__r, analyzedFileSymbol("ComponentParameter.AttributeName"))
		},
	},
	ComponentCall: struct {
		ReceivesAttributes             func(z *analyzer, __r *file.ComponentCall)
		ReceivesAndPlaceholder         func(z *analyzer, __r *file.ComponentCall)
		ElementsWithAndPlaceholder     func(z *analyzer, __r *file.ComponentCall)
		ElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.ComponentCall)
	}{
		ReceivesAttributes: func(z *analyzer, __r *file.ComponentCall) {
			z.Ran(__r, analyzedFileSymbol("ComponentCall.ReceivesAttributes"))
		},
		ReceivesAndPlaceholder: func(z *analyzer, __r *file.ComponentCall) {
			z.Ran(__r, analyzedFileSymbol("ComponentCall.ReceivesAndPlaceholder"))
		},
		ElementsWithAndPlaceholder: func(z *analyzer, __r *file.ComponentCall) {
			z.Ran(__r, analyzedFileSymbol("ComponentCall.ElementsWithAndPlaceholder"))
		},
		ElementSpecsWithAndPlaceholder: func(z *analyzer, __r *file.ComponentCall) {
			z.Ran(__r, analyzedFileSymbol("ComponentCall.ElementSpecsWithAndPlaceholder"))
		},
	},
	ElementSpec: struct {
		Circular func(z *analyzer, __r *file.ElementSpec)
		Type     func(z *analyzer, __r *file.ElementSpec)
	}{
		Circular: func(z *analyzer, __r *file.ElementSpec) {
			z.Ran(__r, analyzedFileSymbol("ElementSpec.Circular"))
		},
		Type: func(z *analyzer, __r *file.ElementSpec) {
			z.Ran(__r, analyzedFileSymbol("ElementSpec.Type"))
		},
	},
}

var requireField = struct {
	Attribute struct {
		Value                 func(z *analyzer, __r *file.Attribute)
		Forwarded             func(z *analyzer, __r *file.Attribute)
		Receivers             func(z *analyzer, __r *file.Attribute)
		ReceivingElementSpecs func(z *analyzer, __r *file.Attribute)
		Type                  func(z *analyzer, __r *file.Attribute)
	}
	Block struct {
	}
	BlockInstance struct {
		Forwarded               func(z *analyzer, __r *file.BlockInstance)
		ContainingElements      func(z *analyzer, __r *file.BlockInstance)
		ContainingElementSpecs  func(z *analyzer, __r *file.BlockInstance)
		CannotForwardAttributes func(z *analyzer, __r *file.BlockInstance)
		Default                 struct {
			AcceptsAttributes              func(z *analyzer, __r *file.BlockInstance)
			ForwardsReceivedAttributes     func(z *analyzer, __r *file.BlockInstance)
			ElementsWithAndPlaceholder     func(z *analyzer, __r *file.BlockInstance)
			ElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.BlockInstance)
			ForwardsAttributes             func(z *analyzer, __r *file.BlockInstance)
			WritesContent                  func(z *analyzer, __r *file.BlockInstance)
			WritesElements                 func(z *analyzer, __r *file.BlockInstance)
		}
	}
	BlockSetter struct {
	}
	BlockSetterInstance struct {
		AcceptsAttributes          func(z *analyzer, __r *file.BlockSetterInstance)
		ForwardsReceivedAttributes func(z *analyzer, __r *file.BlockSetterInstance)
		ForwardsAttributes         func(z *analyzer, __r *file.BlockSetterInstance)
		WritesContent              func(z *analyzer, __r *file.BlockSetterInstance)
		WritesElements             func(z *analyzer, __r *file.BlockSetterInstance)
	}
	Component struct {
		Circular                                func(z *analyzer, __r *file.Component)
		AlwaysAcceptsAttributes                 func(z *analyzer, __r *file.Component)
		AlwaysForwardsReceivedAttributes        func(z *analyzer, __r *file.Component)
		AlwaysForwardsAttributes                func(z *analyzer, __r *file.Component)
		AlwaysWritesContent                     func(z *analyzer, __r *file.Component)
		AlwaysWritesElements                    func(z *analyzer, __r *file.Component)
		PermanentElementsWithAndPlaceholder     func(z *analyzer, __r *file.Component)
		PermanentElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.Component)
	}
	ComponentArgument struct {
		Value func(z *analyzer, __r *file.ComponentArgument)
	}
	ComponentParameter struct {
		InferredType  func(z *analyzer, __r *file.ComponentParameter)
		AttributeType func(z *analyzer, __r *file.ComponentParameter)
		AttributeName func(z *analyzer, __r *file.ComponentParameter)
	}
	ComponentCall struct {
		ReceivesAttributes             func(z *analyzer, __r *file.ComponentCall)
		ReceivesAndPlaceholder         func(z *analyzer, __r *file.ComponentCall)
		ElementsWithAndPlaceholder     func(z *analyzer, __r *file.ComponentCall)
		ElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.ComponentCall)
	}
	ElementSpec struct {
		Circular func(z *analyzer, __r *file.ElementSpec)
		Type     func(z *analyzer, __r *file.ElementSpec)
	}
}{
	Attribute: struct {
		Value                 func(z *analyzer, __r *file.Attribute)
		Forwarded             func(z *analyzer, __r *file.Attribute)
		Receivers             func(z *analyzer, __r *file.Attribute)
		ReceivingElementSpecs func(z *analyzer, __r *file.Attribute)
		Type                  func(z *analyzer, __r *file.Attribute)
	}{
		Value: func(z *analyzer, __r *file.Attribute) {
			z.Require(__r, analyzedFileSymbol("Attribute.Value"))
		},
		Forwarded: func(z *analyzer, __r *file.Attribute) {
			z.Require(__r, analyzedFileSymbol("Attribute.Forwarded"))
		},
		Receivers: func(z *analyzer, __r *file.Attribute) {
			z.Require(__r, analyzedFileSymbol("Attribute.Receivers"))
		},
		ReceivingElementSpecs: func(z *analyzer, __r *file.Attribute) {
			z.Require(__r, analyzedFileSymbol("Attribute.ReceivingElementSpecs"))
		},
		Type: func(z *analyzer, __r *file.Attribute) {
			z.Require(__r, analyzedFileSymbol("Attribute.Type"))
		},
	},
	Block: struct {
	}{},
	BlockInstance: struct {
		Forwarded               func(z *analyzer, __r *file.BlockInstance)
		ContainingElements      func(z *analyzer, __r *file.BlockInstance)
		ContainingElementSpecs  func(z *analyzer, __r *file.BlockInstance)
		CannotForwardAttributes func(z *analyzer, __r *file.BlockInstance)
		Default                 struct {
			AcceptsAttributes              func(z *analyzer, __r *file.BlockInstance)
			ForwardsReceivedAttributes     func(z *analyzer, __r *file.BlockInstance)
			ElementsWithAndPlaceholder     func(z *analyzer, __r *file.BlockInstance)
			ElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.BlockInstance)
			ForwardsAttributes             func(z *analyzer, __r *file.BlockInstance)
			WritesContent                  func(z *analyzer, __r *file.BlockInstance)
			WritesElements                 func(z *analyzer, __r *file.BlockInstance)
		}
	}{
		Forwarded: func(z *analyzer, __r *file.BlockInstance) {
			z.Require(__r, analyzedFileSymbol("BlockInstance.Forwarded"))
		},
		ContainingElements: func(z *analyzer, __r *file.BlockInstance) {
			z.Require(__r, analyzedFileSymbol("BlockInstance.ContainingElements"))
		},
		ContainingElementSpecs: func(z *analyzer, __r *file.BlockInstance) {
			z.Require(__r, analyzedFileSymbol("BlockInstance.ContainingElementSpecs"))
		},
		CannotForwardAttributes: func(z *analyzer, __r *file.BlockInstance) {
			z.Require(__r, analyzedFileSymbol("BlockInstance.CannotForwardAttributes"))
		},
		Default: struct {
			AcceptsAttributes              func(z *analyzer, __r *file.BlockInstance)
			ForwardsReceivedAttributes     func(z *analyzer, __r *file.BlockInstance)
			ElementsWithAndPlaceholder     func(z *analyzer, __r *file.BlockInstance)
			ElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.BlockInstance)
			ForwardsAttributes             func(z *analyzer, __r *file.BlockInstance)
			WritesContent                  func(z *analyzer, __r *file.BlockInstance)
			WritesElements                 func(z *analyzer, __r *file.BlockInstance)
		}{
			AcceptsAttributes: func(z *analyzer, __r *file.BlockInstance) {
				z.Require(__r, analyzedFileSymbol("BlockInstance.Default.AcceptsAttributes"))
			},
			ForwardsReceivedAttributes: func(z *analyzer, __r *file.BlockInstance) {
				z.Require(__r, analyzedFileSymbol("BlockInstance.Default.ForwardsReceivedAttributes"))
			},
			ElementsWithAndPlaceholder: func(z *analyzer, __r *file.BlockInstance) {
				z.Require(__r, analyzedFileSymbol("BlockInstance.Default.ElementsWithAndPlaceholder"))
			},
			ElementSpecsWithAndPlaceholder: func(z *analyzer, __r *file.BlockInstance) {
				z.Require(__r, analyzedFileSymbol("BlockInstance.Default.ElementSpecsWithAndPlaceholder"))
			},
			ForwardsAttributes: func(z *analyzer, __r *file.BlockInstance) {
				z.Require(__r, analyzedFileSymbol("BlockInstance.Default.ForwardsAttributes"))
			},
			WritesContent: func(z *analyzer, __r *file.BlockInstance) {
				z.Require(__r, analyzedFileSymbol("BlockInstance.Default.WritesContent"))
			},
			WritesElements: func(z *analyzer, __r *file.BlockInstance) {
				z.Require(__r, analyzedFileSymbol("BlockInstance.Default.WritesElements"))
			},
		},
	},
	BlockSetter: struct {
	}{},
	BlockSetterInstance: struct {
		AcceptsAttributes          func(z *analyzer, __r *file.BlockSetterInstance)
		ForwardsReceivedAttributes func(z *analyzer, __r *file.BlockSetterInstance)
		ForwardsAttributes         func(z *analyzer, __r *file.BlockSetterInstance)
		WritesContent              func(z *analyzer, __r *file.BlockSetterInstance)
		WritesElements             func(z *analyzer, __r *file.BlockSetterInstance)
	}{
		AcceptsAttributes: func(z *analyzer, __r *file.BlockSetterInstance) {
			z.Require(__r, analyzedFileSymbol("BlockSetterInstance.AcceptsAttributes"))
		},
		ForwardsReceivedAttributes: func(z *analyzer, __r *file.BlockSetterInstance) {
			z.Require(__r, analyzedFileSymbol("BlockSetterInstance.ForwardsReceivedAttributes"))
		},
		ForwardsAttributes: func(z *analyzer, __r *file.BlockSetterInstance) {
			z.Require(__r, analyzedFileSymbol("BlockSetterInstance.ForwardsAttributes"))
		},
		WritesContent: func(z *analyzer, __r *file.BlockSetterInstance) {
			z.Require(__r, analyzedFileSymbol("BlockSetterInstance.WritesContent"))
		},
		WritesElements: func(z *analyzer, __r *file.BlockSetterInstance) {
			z.Require(__r, analyzedFileSymbol("BlockSetterInstance.WritesElements"))
		},
	},
	Component: struct {
		Circular                                func(z *analyzer, __r *file.Component)
		AlwaysAcceptsAttributes                 func(z *analyzer, __r *file.Component)
		AlwaysForwardsReceivedAttributes        func(z *analyzer, __r *file.Component)
		AlwaysForwardsAttributes                func(z *analyzer, __r *file.Component)
		AlwaysWritesContent                     func(z *analyzer, __r *file.Component)
		AlwaysWritesElements                    func(z *analyzer, __r *file.Component)
		PermanentElementsWithAndPlaceholder     func(z *analyzer, __r *file.Component)
		PermanentElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.Component)
	}{
		Circular: func(z *analyzer, __r *file.Component) {
			z.Require(__r, analyzedFileSymbol("Component.Circular"))
		},
		AlwaysAcceptsAttributes: func(z *analyzer, __r *file.Component) {
			z.Require(__r, analyzedFileSymbol("Component.AlwaysAcceptsAttributes"))
		},
		AlwaysForwardsReceivedAttributes: func(z *analyzer, __r *file.Component) {
			z.Require(__r, analyzedFileSymbol("Component.AlwaysForwardsReceivedAttributes"))
		},
		AlwaysForwardsAttributes: func(z *analyzer, __r *file.Component) {
			z.Require(__r, analyzedFileSymbol("Component.AlwaysForwardsAttributes"))
		},
		AlwaysWritesContent: func(z *analyzer, __r *file.Component) {
			z.Require(__r, analyzedFileSymbol("Component.AlwaysWritesContent"))
		},
		AlwaysWritesElements: func(z *analyzer, __r *file.Component) {
			z.Require(__r, analyzedFileSymbol("Component.AlwaysWritesElements"))
		},
		PermanentElementsWithAndPlaceholder: func(z *analyzer, __r *file.Component) {
			z.Require(__r, analyzedFileSymbol("Component.PermanentElementsWithAndPlaceholder"))
		},
		PermanentElementSpecsWithAndPlaceholder: func(z *analyzer, __r *file.Component) {
			z.Require(__r, analyzedFileSymbol("Component.PermanentElementSpecsWithAndPlaceholder"))
		},
	},
	ComponentArgument: struct {
		Value func(z *analyzer, __r *file.ComponentArgument)
	}{
		Value: func(z *analyzer, __r *file.ComponentArgument) {
			z.Require(__r, analyzedFileSymbol("ComponentArgument.Value"))
		},
	},
	ComponentParameter: struct {
		InferredType  func(z *analyzer, __r *file.ComponentParameter)
		AttributeType func(z *analyzer, __r *file.ComponentParameter)
		AttributeName func(z *analyzer, __r *file.ComponentParameter)
	}{
		InferredType: func(z *analyzer, __r *file.ComponentParameter) {
			z.Require(__r, analyzedFileSymbol("ComponentParameter.InferredType"))
		},
		AttributeType: func(z *analyzer, __r *file.ComponentParameter) {
			z.Require(__r, analyzedFileSymbol("ComponentParameter.AttributeType"))
		},
		AttributeName: func(z *analyzer, __r *file.ComponentParameter) {
			z.Require(__r, analyzedFileSymbol("ComponentParameter.AttributeName"))
		},
	},
	ComponentCall: struct {
		ReceivesAttributes             func(z *analyzer, __r *file.ComponentCall)
		ReceivesAndPlaceholder         func(z *analyzer, __r *file.ComponentCall)
		ElementsWithAndPlaceholder     func(z *analyzer, __r *file.ComponentCall)
		ElementSpecsWithAndPlaceholder func(z *analyzer, __r *file.ComponentCall)
	}{
		ReceivesAttributes: func(z *analyzer, __r *file.ComponentCall) {
			z.Require(__r, analyzedFileSymbol("ComponentCall.ReceivesAttributes"))
		},
		ReceivesAndPlaceholder: func(z *analyzer, __r *file.ComponentCall) {
			z.Require(__r, analyzedFileSymbol("ComponentCall.ReceivesAndPlaceholder"))
		},
		ElementsWithAndPlaceholder: func(z *analyzer, __r *file.ComponentCall) {
			z.Require(__r, analyzedFileSymbol("ComponentCall.ElementsWithAndPlaceholder"))
		},
		ElementSpecsWithAndPlaceholder: func(z *analyzer, __r *file.ComponentCall) {
			z.Require(__r, analyzedFileSymbol("ComponentCall.ElementSpecsWithAndPlaceholder"))
		},
	},
	ElementSpec: struct {
		Circular func(z *analyzer, __r *file.ElementSpec)
		Type     func(z *analyzer, __r *file.ElementSpec)
	}{
		Circular: func(z *analyzer, __r *file.ElementSpec) {
			z.Require(__r, analyzedFileSymbol("ElementSpec.Circular"))
		},
		Type: func(z *analyzer, __r *file.ElementSpec) {
			z.Require(__r, analyzedFileSymbol("ElementSpec.Type"))
		},
	},
}
