//go:build generate

package analyze

import (
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
	"testing"
)

func TestGenerateAssertions(t *testing.T) {
	requirers, err := loadRequirers()
	if err != nil {
		t.Fatalf("failed to load requirers: %v", err)
	}

	f, err := os.Create("assertions.go")
	if err != nil {
		t.Fatalf("failed to create assertions.go: %v", err)
	}

	pkgName := os.Getenv("GOPACKAGE")
	if pkgName == "" {
		t.Fatal("GOPACKAGE is not set")
	}

	fmt.Fprintln(f, "package "+pkgName)
	fmt.Fprintln(f)
	fmt.Fprintln(f, "import (")
	fmt.Fprintln(f, "\t\"github.com/mavolin/corgi/v2/escape/attrtype\"")
	fmt.Fprintln(f, "\t\"github.com/mavolin/corgi/v2/escape/elemtype\"")
	fmt.Fprintln(f, "\t\"github.com/mavolin/corgi/v2/file\"")
	fmt.Fprintln(f, "\t\"github.com/mavolin/corgi/v2/file/ast\"")
	fmt.Fprintln(f, ")")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "// Code generated by go test -run GenerateAssertions -tags generate; DO NOT EDIT.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "//go:generate go test -run GenerateAssertions -tags generate")
	fmt.Fprintln(f)
	writeGetVar(f, requirers)
	fmt.Fprintln(f)
	writeRequireVar(f, requirers)
	fmt.Fprintln(f)
	fmt.Fprintln(f, "type analyzedFileSymbol string")
	fmt.Fprintln(f)
	writeAnalyzedVar(f, requirers)
	fmt.Fprintln(f)
	writeRequireFieldVar(f, requirers)

	if err := f.Close(); err != nil {
		t.Fatalf("failed to close assertions.go: %v", err)
	}
}

// ============================================================================
// get
// ======================================================================================

func writeGetVar(w io.Writer, rs []requireableGroup) {
	writeVar(w, rs, "get", writeGetSymbolType, writeGetter, options{})
}

func writeGetSymbolType(w io.Writer, _ int, chain []string, s requireableSymbol) {
	rootType := chain[0]

	fmt.Fprint(w, "func(z *analyzer, __r *file.")
	fmt.Fprint(w, rootType)
	for _, p := range s.Params {
		fmt.Fprint(w, ", "+p[0]+" "+p[1])
	}
	fmt.Fprint(w, ") ")
	fmt.Fprint(w, s.Type)
}

func writeGetter(w io.Writer, indentation int, chain []string, s requireableSymbol) {
	indent := strings.Repeat("\t", indentation)

	writeGetSymbolType(w, indentation, chain, s)
	fmt.Fprintln(w, " {")

	fmt.Fprintln(w, indent+"\trequire."+strings.Join(chain, ".")+"(z, __r)")

	fmt.Fprint(w, indent+"\treturn __r."+strings.Join(chain[1:], "."))
	if s.Method {
		fmt.Fprint(w, "(")
		for i, p := range s.Params {
			if i > 0 {
				fmt.Fprint(w, ", ")
			}
			fmt.Fprint(w, p[0])
		}
		fmt.Fprint(w, ")")
	}
	fmt.Fprintln(w)

	fmt.Fprint(w, indent+"}")
}

// ============================================================================
// require
// ======================================================================================

func writeRequireVar(w io.Writer, rs []requireableGroup) {
	writeVar(w, rs, "require", writeRequirerSymbolType, writeRequirerSymbolValue, options{
		init: true,
	})
}

func writeRequirerSymbolType(w io.Writer, _ int, chain []string, _ requireableSymbol) {
	rootType := chain[0]

	fmt.Fprint(w, "func(*analyzer, *file."+rootType+")")
}

func writeRequirerSymbolValue(w io.Writer, _ int, chain []string, _ requireableSymbol) {
	fmt.Fprint(w, "requirer{}."+strings.Join(chain, "_"))
}

// ============================================================================
// analyzed
// ======================================================================================

func writeAnalyzedVar(w io.Writer, rs []requireableGroup) {
	writeVar(w, rs, "analyzed", writeMarkSymbolType, writeMarkSymbolValue, options{
		ignoreMethods: true,
	})
}

func writeMarkSymbolType(w io.Writer, _ int, chain []string, _ requireableSymbol) {
	rootType := chain[0]

	fmt.Fprint(w, "func(z *analyzer, __r *file."+rootType+")")
}

func writeMarkSymbolValue(w io.Writer, indentation int, chain []string, s requireableSymbol) {
	indent := strings.Repeat("\t", indentation)

	writeMarkSymbolType(w, indentation, chain, s)
	fmt.Fprintln(w, " {")

	fmt.Fprint(w, indent+"\tz.Ran(__r, ")
	writeRequireKey(w, chain)
	fmt.Fprintln(w, ")")

	fmt.Fprint(w, indent+"}")
}

// ============================================================================
// requireField
// ======================================================================================

func writeRequireFieldVar(w io.Writer, rs []requireableGroup) {
	writeVar(w, rs, "requireField", writeRequireFieldSymbolType, writeRequireFieldSymbolValue, options{
		ignoreMethods: true,
	})
}

func writeRequireFieldSymbolType(w io.Writer, _ int, chain []string, _ requireableSymbol) {
	rootType := chain[0]
	fmt.Fprint(w, "func(z *analyzer, __r *file."+rootType+")")
}

func writeRequireFieldSymbolValue(w io.Writer, indentation int, chain []string, s requireableSymbol) {
	indent := strings.Repeat("\t", indentation)

	writeRequireFieldSymbolType(w, indentation, chain, s)
	fmt.Fprintln(w, " {")

	fmt.Fprint(w, indent+"\tz.Require(__r, ")
	writeRequireKey(w, chain)
	fmt.Fprintln(w, ")")

	fmt.Fprint(w, indent+"}")
}

func writeRequireKey(w io.Writer, chain []string) {
	fmt.Fprint(w, "analyzedFileSymbol("+strconv.Quote(strings.Join(chain, "."))+")")
}

// ============================================================================
// Helpers
// ======================================================================================

type options struct {
	init          bool
	ignoreMethods bool
}

func writeVar(
	w io.Writer, rs []requireableGroup, name string,
	writeSymbolType func(w io.Writer, indentation int, chain []string, s requireableSymbol),
	writeSymbolValue func(w io.Writer, indentation int, chain []string, s requireableSymbol),
	o options,
) {
	fmt.Fprint(w, "var "+name+" ")
	if !o.init {
		fmt.Fprint(w, "= ")
	}
	writeType(w, 0, rs, writeSymbolType, o)

	indentation := 0
	if o.init {
		fmt.Fprintln(w)
		fmt.Fprintln(w, "func init() {")

		fmt.Fprint(w, "\t"+name+" = ")
		writeType(w, 1, rs, writeSymbolType, o)
		indentation = 1
	}

	indent := strings.Repeat("\t", indentation)

	fmt.Fprintln(w, "{")
	for _, r := range rs {
		fmt.Fprint(w, indent+"\t"+r.Name+": ")
		writeGroupValue(w, indentation+1, []string{r.Name}, r, writeSymbolType, writeSymbolValue, o)
		fmt.Fprintln(w, ",")
	}
	fmt.Fprintln(w, indent+"}")

	if o.init {
		fmt.Fprintln(w, "}")
	}
}

func writeType(
	w io.Writer, indentation int, rs []requireableGroup,
	writeSymbolType func(w io.Writer, indentation int, chain []string, s requireableSymbol),
	o options,
) {
	indent := strings.Repeat("\t", indentation)

	fmt.Fprintln(w, "struct {")
	for _, r := range rs {
		fmt.Fprint(w, indent+"\t"+r.Name+" ")
		writeGroupType(w, indentation+1, []string{r.Name}, r, writeSymbolType, o)
		fmt.Fprintln(w)
	}
	fmt.Fprint(w, indent+"}")
}

func writeGroupType(
	w io.Writer, indentation int, chain []string, r requireableGroup,
	writeSymbolType func(w io.Writer, indentation int, chain []string, s requireableSymbol),
	o options,
) {
	indent := strings.Repeat("\t", indentation)

	fmt.Fprintln(w, "struct {")
	for _, s := range r.Symbols {
		if o.ignoreMethods && s.Method {
			continue
		}
		fmt.Fprint(w, indent+"\t"+s.Name+" ")
		writeSymbolType(w, indentation+1, append(chain, s.Name), s)
		fmt.Fprintln(w)
	}
	for _, f := range r.Fields {
		fmt.Fprint(w, indent+"\t"+f.Name+" ")
		writeGroupType(w, indentation+1, append(chain, f.Name), f, writeSymbolType, o)
		fmt.Fprintln(w)
	}
	fmt.Fprint(w, indent+"}")
}

func writeGroupValue(
	w io.Writer, indentation int, chain []string, g requireableGroup,
	writeSymbolType func(w io.Writer, indentation int, chain []string, s requireableSymbol),
	writeSymbolValue func(w io.Writer, indentation int, chain []string, s requireableSymbol),
	o options,
) {
	indent := strings.Repeat("\t", indentation)

	writeGroupType(w, indentation, chain, g, writeSymbolType, o)
	fmt.Fprintln(w, "{")
	for _, s := range g.Symbols {
		if o.ignoreMethods && s.Method {
			continue
		}
		fmt.Fprint(w, indent+"\t"+s.Name+": ")
		writeSymbolValue(w, indentation+1, append(chain, s.Name), s)
		fmt.Fprintln(w, ",")
	}
	for _, f := range g.Fields {
		fmt.Fprint(w, indent+"\t"+f.Name+": ")
		writeGroupValue(w, indentation+1, append(chain, f.Name), f, writeSymbolType, writeSymbolValue, o)
		fmt.Fprintln(w, ",")
	}
	fmt.Fprint(w, indent+"}")
}
