// Code generated by "stringer -type Token"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Error-0]
	_ = x[EOF-1]
	_ = x[Indent-2]
	_ = x[Dedent-3]
	_ = x[Element-4]
	_ = x[Ident-5]
	_ = x[Literal-6]
	_ = x[Expression-7]
	_ = x[Text-8]
	_ = x[CodeStart-9]
	_ = x[Code-10]
	_ = x[Ternary-11]
	_ = x[TernaryElse-12]
	_ = x[NilCheck-13]
	_ = x[LParen-14]
	_ = x[RParen-15]
	_ = x[LBrace-16]
	_ = x[RBrace-17]
	_ = x[LBracket-18]
	_ = x[RBracket-19]
	_ = x[Assign-20]
	_ = x[AssignNoEscape-21]
	_ = x[Comma-22]
	_ = x[Comment-23]
	_ = x[CorgiComment-24]
	_ = x[Import-25]
	_ = x[Func-26]
	_ = x[Extend-27]
	_ = x[Include-28]
	_ = x[Use-29]
	_ = x[Block-30]
	_ = x[Append-31]
	_ = x[Prepend-32]
	_ = x[If-33]
	_ = x[IfBlock-34]
	_ = x[ElseIf-35]
	_ = x[Else-36]
	_ = x[Switch-37]
	_ = x[Case-38]
	_ = x[Default-39]
	_ = x[For-40]
	_ = x[Range-41]
	_ = x[While-42]
	_ = x[Mixin-43]
	_ = x[MixinCall-44]
	_ = x[MixinMainBlockShorthand-45]
	_ = x[And-46]
	_ = x[AndPlaceholder-47]
	_ = x[Div-48]
	_ = x[Class-49]
	_ = x[ID-50]
	_ = x[BlockExpansion-51]
	_ = x[Filter-52]
	_ = x[DotBlock-53]
	_ = x[DotBlockLine-54]
	_ = x[Pipe-55]
	_ = x[Interpolation-56]
	_ = x[UnescapedInterpolation-57]
	_ = x[TagVoid-58]
}

const _Token_name = "ErrorEOFIndentDedentElementIdentLiteralExpressionTextCodeStartCodeTernaryTernaryElseNilCheckLParenRParenLBraceRBraceLBracketRBracketAssignAssignNoEscapeCommaCommentCorgiCommentImportFuncExtendIncludeUseBlockAppendPrependIfIfBlockElseIfElseSwitchCaseDefaultForRangeWhileMixinMixinCallMixinBlockShorthandAndAndPlaceholderDivClassIDBlockExpansionFilterDotBlockDotBlockLinePipeHashNoEscapeTagVoid"

var _Token_index = [...]uint16{0, 5, 8, 14, 20, 27, 32, 39, 49, 53, 62, 66, 73, 84, 92, 98, 104, 110, 116, 124, 132, 138, 152, 157, 164, 176, 182, 186, 192, 199, 202, 207, 213, 220, 222, 229, 235, 239, 245, 249, 256, 259, 264, 269, 274, 283, 302, 305, 319, 322, 327, 329, 343, 349, 357, 369, 373, 377, 385, 392}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
