{
    package internal

    type ErrList = errList
    type ParserError = parserError
}

AST <- init docI:PackageDoc EMPTY_LINE* pkgI:Package EMPTY_LINE* scopeI:GlobalScope EMPTY_LINE* EOF {
    return &ast.AST{
        PackageDoc:       optCast[[]*ast.DevComment](docI),
        PackageDirective: optCast[*ast.PackageDirective](pkgI),
        Scope:            scopeI.(*ast.Scope),
    }, nil
}

init <- #{
    newState(c)
    return nil
}
