//go:build generate

package isstdlib

import (
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"strings"
	"testing"
)

const out = "detector.go"

// TestGenerate is a pseudo-test that generates the detector.go file.
func TestGenerate(t *testing.T) {
	goroot := os.Getenv("GOROOT")
	if goroot == "" {
		t.Fatal("GOROOT is not set")
	}

	pkg := os.Getenv("GOPACKAGE")
	if pkg == "" {
		t.Fatal("GOPACKAGE is not set")
	}

	packages, err := collectPackages(goroot)
	if err != nil {
		t.Fatal(err)
	}

	f, err := os.Create(out)
	if err != nil {
		t.Fatalf("opening output file: %s\n", err)
	}
	defer f.Close()

	writeFile(f, pkg, packages)
}

func collectPackages(goroot string) ([]string, error) {
	packages := make([]string, 0, 256)

	err := fs.WalkDir(os.DirFS(filepath.Join(goroot, "src")), ".", func(p string, d fs.DirEntry, err error) error {
		if p == "." {
			return nil
		}
		if err != nil {
			return err
		}

		name := strings.TrimPrefix(p, "./")
		base := path.Base(name)
		if d.IsDir() {
			if base == "internal" || base == "vendor" || base == "testdata" {
				return fs.SkipDir
			}
			packages = append(packages, name)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walking GOROOT/src: %w", err)
	}
	return packages, nil
}

func writeFile(w io.Writer, pkg string, stdlib []string) {
	fmt.Fprintln(w, "package", pkg)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// Code generated by go test -run=Generate -tags generate; DO NOT EDIT.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// IsStdlib heuristically detects already known Go stdlib packages, so that")
	fmt.Fprintln(w, "// we don't unnecessarily preload them.")
	fmt.Fprintln(w, "func IsStdlib(path string) bool {")
	fmt.Fprintln(w, "\tswitch path {")
	for _, pkg := range stdlib {
		fmt.Fprintf(w, "\tcase %q:\n", pkg)
	}
	fmt.Fprintln(w, "\tdefault:")
	fmt.Fprintln(w, "\t\treturn false")
	fmt.Fprintln(w, "\t}")
	fmt.Fprintln(w, "\treturn true")
	fmt.Fprintln(w, "}")
}
