//go:build generate

package switches

import (
	"fmt"
	"go/types"
	"io"
	"os"
	"slices"
	"strconv"
	"strings"
	"testing"

	"golang.org/x/tools/go/packages"
)

const out = "functions.go"

type (
	SumType struct {
		name     string
		typ      string
		variants []variant
	}
	variant struct {
		name string
		typ  string
	}
)

func TestGenerate(t *testing.T) {
	outPkgName := os.Getenv("GOPACKAGE")
	if outPkgName == "" {
		t.Fatal("GOPACKAGE is not set")
	}

	pkgs, err := loadPackages()
	if err != nil {
		t.Fatal(err)
	}

	file := output{
		imports: make([]string, 0, len(pkgs)),
	}

	for _, pkg := range pkgs {
		pkgSumTypes, err := collectSumTypes(pkg)
		if err != nil {
			t.Fatal(err)
		}
		file.imports = append(file.imports, pkg.PkgPath)
		file.sumTypes = append(file.sumTypes, pkgSumTypes...)
	}

	f, err := os.Create(out)
	if err != nil {
		t.Fatalf("output file: %s", err)
	}
	defer f.Close()

	writeFile(f, outPkgName, file)
}

func loadPackages() ([]*packages.Package, error) {
	pkgs, err := packages.Load(&packages.Config{
		Mode: packages.NeedTypes | packages.NeedName,
	}, "../", "../ast")
	if err != nil {
		return nil, fmt.Errorf("failed to load packages: %w", err)
	} else if len(pkgs) != 2 {
		return nil, fmt.Errorf("expected two packages, got %d", len(pkgs))
	}

	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			return nil, fmt.Errorf("package %s has errors: %v", pkg.Name, pkg.Errors)
		}
	}
	return pkgs, nil
}

// collectSumTypes finds all sum types in the package and their variants
func collectSumTypes(pkg *packages.Package) ([]SumType, error) {
	scope := pkg.Types.Scope()

	sumTypes := make([]SumType, 0, 32)
	for _, sumName := range scope.Names() {
		sumObj := scope.Lookup(sumName)
		if sumObj == nil {
			continue
		}

		sumIface, _ := sumObj.Type().Underlying().(*types.Interface)
		if sumIface == nil {
			continue
		} else if !isSumType(sumIface) {
			continue
		}

		sum := SumType{
			name: sumName,
			typ:  pkg.Name + "." + sumName,
		}

		for _, variantName := range scope.Names() {
			variantObj := scope.Lookup(variantName)
			if variantObj == nil {
				continue
			}

			namedVariant, ok := variantObj.Type().(*types.Named)
			if !ok {
				continue
			} else if _, isIface := namedVariant.Underlying().(*types.Interface); isIface {
				continue
			}

			if types.Implements(namedVariant, sumIface) {
				sum.variants = append(sum.variants, variant{
					name: variantName,
					typ:  pkg.Name + "." + variantName,
				})
			} else if ptr := types.NewPointer(namedVariant); types.Implements(ptr, sumIface) {
				sum.variants = append(sum.variants, variant{
					name: variantName,
					typ:  "*" + pkg.Name + "." + variantName,
				})
			}
		}

		if len(sum.variants) == 0 {
			return nil, fmt.Errorf("sum type %s has no variants", sumName)
		}

		slices.SortFunc(sum.variants, func(a, b variant) int {
			return strings.Compare(a.name, b.name)
		})

		sumTypes = append(sumTypes, sum)
	}

	return sumTypes, nil
}

func isSumType(ifaceType *types.Interface) bool {
	for method := range ifaceType.Methods() {
		if strings.HasPrefix(method.Name(), "_") {
			return true
		}
	}
	return false
}

type output struct {
	imports  []string
	sumTypes []SumType
}

func writeFile(w io.Writer, pkgName string, o output) {
	slices.Sort(o.imports)
	slices.SortFunc(o.sumTypes, func(a, b SumType) int {
		return strings.Compare(a.name, b.name)
	})

	fmt.Fprintln(w, "package "+pkgName)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "import (")
	fmt.Fprintln(w, "\t\"fmt\"")
	fmt.Fprintln(w)
	for _, imp := range o.imports {
		fmt.Fprintln(w, "\t"+strconv.Quote(imp))
	}
	fmt.Fprintln(w, ")")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// Code generated by go test -run Generate -tags generate; DO NOT EDIT.")
	for _, t := range o.sumTypes {
		fmt.Fprintln(w)
		fmt.Fprintln(w, "func "+t.name+"(n "+t.typ+",")
		for _, variant := range t.variants {
			fmt.Fprintln(w, "\t"+variant.name+" func("+variant.typ+"),")
		}
		fmt.Fprintln(w, ") {")
		fmt.Fprintln(w, "\tswitch n := n.(type) {")
		for _, variant := range t.variants {
			fmt.Fprintln(w, "\tcase "+variant.typ+":")
			fmt.Fprintln(w, "\t\t"+variant.name+"(n)")
		}
		fmt.Fprintln(w, "\tdefault:")
		fmt.Fprintln(w, "\t\tpanic(fmt.Sprintf(\""+t.name+": unknown variant %T: please rerun go generate\", n))")
		fmt.Fprintln(w, "\t}")
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w)

		fmt.Fprintln(w, "func "+t.name+"R[T any](n "+t.typ+",")
		for _, variant := range t.variants {
			fmt.Fprintln(w, "\t"+variant.name+" func("+variant.typ+") T,")
		}
		fmt.Fprintln(w, ") T {")
		fmt.Fprintln(w, "\tswitch n := n.(type) {")
		for _, variant := range t.variants {
			fmt.Fprintln(w, "\tcase "+variant.typ+":")
			fmt.Fprintln(w, "\t\treturn "+variant.name+"(n)")
		}
		fmt.Fprintln(w, "\tdefault:")
		fmt.Fprintln(w, "\t\tpanic(fmt.Sprintf(\""+t.name+": unknown variant %T: please rerun go generate\", n))")
		fmt.Fprintln(w, "\t}")
		fmt.Fprintln(w, "}")
	}
}
