// Package switches provides functions for exhaustive switching over the sum
// types in package ast.
//
// The switching functions are generated using go generate.
//
// Since the sum types may evolve over time, getting extended with new types,
// this package is expressly exempt from the usual stability guarantee.
// More precisely, a minor version increment allows a breaking change in the
// signatures of the switching functions.
// This, of course, is intended breakage to warn users relying on an exhaustive
// switch that they need to handle a new type.
// All other compatibility guarantees remain untouched.
// Patch version increments do not allow breaking changes.
package switches

import (
	"fmt"

	"github.com/mavolin/corgi/v2/file"
	"github.com/mavolin/corgi/v2/file/ast"
)

// Code generated by the line below; DO NOT EDIT.

//go:generate go test -run Generate -tags=generate

func AndPlaceholderWriter(n ast.AndPlaceholderWriter,
	AndPlaceholder func(*ast.AndPlaceholder),
	ComponentCall func(*ast.ComponentCall),
) {
	switch n := n.(type) {
	case *ast.AndPlaceholder:
		AndPlaceholder(n)
	case *ast.ComponentCall:
		ComponentCall(n)
	default:
		panic(fmt.Sprintf("AndPlaceholderWriter: unknown variant %T: please rerun go generate", n))
	}
}

func AndPlaceholderWriterR[T any](n ast.AndPlaceholderWriter,
	AndPlaceholder func(*ast.AndPlaceholder) T,
	ComponentCall func(*ast.ComponentCall) T,
) T {
	switch n := n.(type) {
	case *ast.AndPlaceholder:
		return AndPlaceholder(n)
	case *ast.ComponentCall:
		return ComponentCall(n)
	default:
		panic(fmt.Sprintf("AndPlaceholderWriter: unknown variant %T: please rerun go generate", n))
	}
}

func Argument(n ast.Argument,
	AndPlaceholder func(*ast.AndPlaceholder),
	ClassShorthand func(*ast.ClassShorthand),
	ComponentArgument func(*ast.ComponentArgument),
	IDShorthand func(*ast.IDShorthand),
	NamedAttribute func(*ast.NamedAttribute),
) {
	switch n := n.(type) {
	case *ast.AndPlaceholder:
		AndPlaceholder(n)
	case *ast.ClassShorthand:
		ClassShorthand(n)
	case *ast.ComponentArgument:
		ComponentArgument(n)
	case *ast.IDShorthand:
		IDShorthand(n)
	case *ast.NamedAttribute:
		NamedAttribute(n)
	default:
		panic(fmt.Sprintf("Argument: unknown variant %T: please rerun go generate", n))
	}
}

func ArgumentR[T any](n ast.Argument,
	AndPlaceholder func(*ast.AndPlaceholder) T,
	ClassShorthand func(*ast.ClassShorthand) T,
	ComponentArgument func(*ast.ComponentArgument) T,
	IDShorthand func(*ast.IDShorthand) T,
	NamedAttribute func(*ast.NamedAttribute) T,
) T {
	switch n := n.(type) {
	case *ast.AndPlaceholder:
		return AndPlaceholder(n)
	case *ast.ClassShorthand:
		return ClassShorthand(n)
	case *ast.ComponentArgument:
		return ComponentArgument(n)
	case *ast.IDShorthand:
		return IDShorthand(n)
	case *ast.NamedAttribute:
		return NamedAttribute(n)
	default:
		panic(fmt.Sprintf("Argument: unknown variant %T: please rerun go generate", n))
	}
}

func Attribute(n ast.Attribute,
	AndPlaceholder func(*ast.AndPlaceholder),
	ClassShorthand func(*ast.ClassShorthand),
	IDShorthand func(*ast.IDShorthand),
	NamedAttribute func(*ast.NamedAttribute),
) {
	switch n := n.(type) {
	case *ast.AndPlaceholder:
		AndPlaceholder(n)
	case *ast.ClassShorthand:
		ClassShorthand(n)
	case *ast.IDShorthand:
		IDShorthand(n)
	case *ast.NamedAttribute:
		NamedAttribute(n)
	default:
		panic(fmt.Sprintf("Attribute: unknown variant %T: please rerun go generate", n))
	}
}

func AttributeR[T any](n ast.Attribute,
	AndPlaceholder func(*ast.AndPlaceholder) T,
	ClassShorthand func(*ast.ClassShorthand) T,
	IDShorthand func(*ast.IDShorthand) T,
	NamedAttribute func(*ast.NamedAttribute) T,
) T {
	switch n := n.(type) {
	case *ast.AndPlaceholder:
		return AndPlaceholder(n)
	case *ast.ClassShorthand:
		return ClassShorthand(n)
	case *ast.IDShorthand:
		return IDShorthand(n)
	case *ast.NamedAttribute:
		return NamedAttribute(n)
	default:
		panic(fmt.Sprintf("Attribute: unknown variant %T: please rerun go generate", n))
	}
}

func AttributeInhibitor(n ast.AttributeInhibitor,
	Block func(*ast.Block),
	BlockSetterAttributeInhibitor func(*ast.BlockSetterAttributeInhibitor),
	CharacterEscape func(*ast.CharacterEscape),
	CharacterReference func(*ast.CharacterReference),
	ComponentCall func(*ast.ComponentCall),
	Doctype func(*ast.Doctype),
	Element func(*ast.Element),
	ExpressionInterpolation func(*ast.ExpressionInterpolation),
	RawElement func(*ast.RawElement),
	Text func(*ast.Text),
) {
	switch n := n.(type) {
	case *ast.Block:
		Block(n)
	case *ast.BlockSetterAttributeInhibitor:
		BlockSetterAttributeInhibitor(n)
	case *ast.CharacterEscape:
		CharacterEscape(n)
	case *ast.CharacterReference:
		CharacterReference(n)
	case *ast.ComponentCall:
		ComponentCall(n)
	case *ast.Doctype:
		Doctype(n)
	case *ast.Element:
		Element(n)
	case *ast.ExpressionInterpolation:
		ExpressionInterpolation(n)
	case *ast.RawElement:
		RawElement(n)
	case *ast.Text:
		Text(n)
	default:
		panic(fmt.Sprintf("AttributeInhibitor: unknown variant %T: please rerun go generate", n))
	}
}

func AttributeInhibitorR[T any](n ast.AttributeInhibitor,
	Block func(*ast.Block) T,
	BlockSetterAttributeInhibitor func(*ast.BlockSetterAttributeInhibitor) T,
	CharacterEscape func(*ast.CharacterEscape) T,
	CharacterReference func(*ast.CharacterReference) T,
	ComponentCall func(*ast.ComponentCall) T,
	Doctype func(*ast.Doctype) T,
	Element func(*ast.Element) T,
	ExpressionInterpolation func(*ast.ExpressionInterpolation) T,
	RawElement func(*ast.RawElement) T,
	Text func(*ast.Text) T,
) T {
	switch n := n.(type) {
	case *ast.Block:
		return Block(n)
	case *ast.BlockSetterAttributeInhibitor:
		return BlockSetterAttributeInhibitor(n)
	case *ast.CharacterEscape:
		return CharacterEscape(n)
	case *ast.CharacterReference:
		return CharacterReference(n)
	case *ast.ComponentCall:
		return ComponentCall(n)
	case *ast.Doctype:
		return Doctype(n)
	case *ast.Element:
		return Element(n)
	case *ast.ExpressionInterpolation:
		return ExpressionInterpolation(n)
	case *ast.RawElement:
		return RawElement(n)
	case *ast.Text:
		return Text(n)
	default:
		panic(fmt.Sprintf("AttributeInhibitor: unknown variant %T: please rerun go generate", n))
	}
}

func AttributeReceiver(n ast.AttributeReceiver,
	AndPlaceholderAttributeReceiver func(*ast.AndPlaceholderAttributeReceiver),
	BlockSetterContainingElement func(*ast.BlockSetterContainingElement),
	Element func(*ast.Element),
) {
	switch n := n.(type) {
	case *ast.AndPlaceholderAttributeReceiver:
		AndPlaceholderAttributeReceiver(n)
	case *ast.BlockSetterContainingElement:
		BlockSetterContainingElement(n)
	case *ast.Element:
		Element(n)
	default:
		panic(fmt.Sprintf("AttributeReceiver: unknown variant %T: please rerun go generate", n))
	}
}

func AttributeReceiverR[T any](n ast.AttributeReceiver,
	AndPlaceholderAttributeReceiver func(*ast.AndPlaceholderAttributeReceiver) T,
	BlockSetterContainingElement func(*ast.BlockSetterContainingElement) T,
	Element func(*ast.Element) T,
) T {
	switch n := n.(type) {
	case *ast.AndPlaceholderAttributeReceiver:
		return AndPlaceholderAttributeReceiver(n)
	case *ast.BlockSetterContainingElement:
		return BlockSetterContainingElement(n)
	case *ast.Element:
		return Element(n)
	default:
		panic(fmt.Sprintf("AttributeReceiver: unknown variant %T: please rerun go generate", n))
	}
}

func AttributeSelector(n ast.AttributeSelector,
	BasicAttributeSelector func(*ast.BasicAttributeSelector),
	RegexpAttributeSelector func(*ast.RegexpAttributeSelector),
) {
	switch n := n.(type) {
	case *ast.BasicAttributeSelector:
		BasicAttributeSelector(n)
	case *ast.RegexpAttributeSelector:
		RegexpAttributeSelector(n)
	default:
		panic(fmt.Sprintf("AttributeSelector: unknown variant %T: please rerun go generate", n))
	}
}

func AttributeSelectorR[T any](n ast.AttributeSelector,
	BasicAttributeSelector func(*ast.BasicAttributeSelector) T,
	RegexpAttributeSelector func(*ast.RegexpAttributeSelector) T,
) T {
	switch n := n.(type) {
	case *ast.BasicAttributeSelector:
		return BasicAttributeSelector(n)
	case *ast.RegexpAttributeSelector:
		return RegexpAttributeSelector(n)
	default:
		panic(fmt.Sprintf("AttributeSelector: unknown variant %T: please rerun go generate", n))
	}
}

func AttributeValue(n ast.AttributeValue,
	ExpressionAttributeValue func(*ast.ExpressionAttributeValue),
	TypedAttributeValue func(*ast.TypedAttributeValue),
) {
	switch n := n.(type) {
	case *ast.ExpressionAttributeValue:
		ExpressionAttributeValue(n)
	case *ast.TypedAttributeValue:
		TypedAttributeValue(n)
	default:
		panic(fmt.Sprintf("AttributeValue: unknown variant %T: please rerun go generate", n))
	}
}

func AttributeValueR[T any](n ast.AttributeValue,
	ExpressionAttributeValue func(*ast.ExpressionAttributeValue) T,
	TypedAttributeValue func(*ast.TypedAttributeValue) T,
) T {
	switch n := n.(type) {
	case *ast.ExpressionAttributeValue:
		return ExpressionAttributeValue(n)
	case *ast.TypedAttributeValue:
		return TypedAttributeValue(n)
	default:
		panic(fmt.Sprintf("AttributeValue: unknown variant %T: please rerun go generate", n))
	}
}

func AttributeWriter(n ast.AttributeWriter,
	ClassShorthand func(*ast.ClassShorthand),
	ComponentCall func(*ast.ComponentCall),
	IDShorthand func(*ast.IDShorthand),
	NamedAttribute func(*ast.NamedAttribute),
) {
	switch n := n.(type) {
	case *ast.ClassShorthand:
		ClassShorthand(n)
	case *ast.ComponentCall:
		ComponentCall(n)
	case *ast.IDShorthand:
		IDShorthand(n)
	case *ast.NamedAttribute:
		NamedAttribute(n)
	default:
		panic(fmt.Sprintf("AttributeWriter: unknown variant %T: please rerun go generate", n))
	}
}

func AttributeWriterR[T any](n ast.AttributeWriter,
	ClassShorthand func(*ast.ClassShorthand) T,
	ComponentCall func(*ast.ComponentCall) T,
	IDShorthand func(*ast.IDShorthand) T,
	NamedAttribute func(*ast.NamedAttribute) T,
) T {
	switch n := n.(type) {
	case *ast.ClassShorthand:
		return ClassShorthand(n)
	case *ast.ComponentCall:
		return ComponentCall(n)
	case *ast.IDShorthand:
		return IDShorthand(n)
	case *ast.NamedAttribute:
		return NamedAttribute(n)
	default:
		panic(fmt.Sprintf("AttributeWriter: unknown variant %T: please rerun go generate", n))
	}
}

func BlockSetter(n ast.BlockSetter,
	DefaultBlockShorthand func(*ast.DefaultBlockShorthand),
	With func(*ast.With),
) {
	switch n := n.(type) {
	case *ast.DefaultBlockShorthand:
		DefaultBlockShorthand(n)
	case *ast.With:
		With(n)
	default:
		panic(fmt.Sprintf("BlockSetter: unknown variant %T: please rerun go generate", n))
	}
}

func BlockSetterR[T any](n ast.BlockSetter,
	DefaultBlockShorthand func(*ast.DefaultBlockShorthand) T,
	With func(*ast.With) T,
) T {
	switch n := n.(type) {
	case *ast.DefaultBlockShorthand:
		return DefaultBlockShorthand(n)
	case *ast.With:
		return With(n)
	default:
		panic(fmt.Sprintf("BlockSetter: unknown variant %T: please rerun go generate", n))
	}
}

func Body(n ast.Body,
	BracketText func(*ast.BracketText),
	Scope func(*ast.Scope),
) {
	switch n := n.(type) {
	case *ast.BracketText:
		BracketText(n)
	case *ast.Scope:
		Scope(n)
	default:
		panic(fmt.Sprintf("Body: unknown variant %T: please rerun go generate", n))
	}
}

func BodyR[T any](n ast.Body,
	BracketText func(*ast.BracketText) T,
	Scope func(*ast.Scope) T,
) T {
	switch n := n.(type) {
	case *ast.BracketText:
		return BracketText(n)
	case *ast.Scope:
		return Scope(n)
	default:
		panic(fmt.Sprintf("Body: unknown variant %T: please rerun go generate", n))
	}
}

func CodeNode(n ast.CodeNode,
	BlockFunction func(*ast.BlockFunction),
	ComponentCall func(*ast.ComponentCall),
	GoCode func(*ast.GoCode),
	String func(*ast.String),
	Ternary func(*ast.Ternary),
	ZeroCoalescing func(*ast.ZeroCoalescing),
) {
	switch n := n.(type) {
	case *ast.BlockFunction:
		BlockFunction(n)
	case *ast.ComponentCall:
		ComponentCall(n)
	case *ast.GoCode:
		GoCode(n)
	case *ast.String:
		String(n)
	case *ast.Ternary:
		Ternary(n)
	case *ast.ZeroCoalescing:
		ZeroCoalescing(n)
	default:
		panic(fmt.Sprintf("CodeNode: unknown variant %T: please rerun go generate", n))
	}
}

func CodeNodeR[T any](n ast.CodeNode,
	BlockFunction func(*ast.BlockFunction) T,
	ComponentCall func(*ast.ComponentCall) T,
	GoCode func(*ast.GoCode) T,
	String func(*ast.String) T,
	Ternary func(*ast.Ternary) T,
	ZeroCoalescing func(*ast.ZeroCoalescing) T,
) T {
	switch n := n.(type) {
	case *ast.BlockFunction:
		return BlockFunction(n)
	case *ast.ComponentCall:
		return ComponentCall(n)
	case *ast.GoCode:
		return GoCode(n)
	case *ast.String:
		return String(n)
	case *ast.Ternary:
		return Ternary(n)
	case *ast.ZeroCoalescing:
		return ZeroCoalescing(n)
	default:
		panic(fmt.Sprintf("CodeNode: unknown variant %T: please rerun go generate", n))
	}
}

func ComponentBody(n ast.ComponentBody,
	BracketText func(*ast.BracketText),
	Extend func(*ast.Extend),
	Scope func(*ast.Scope),
) {
	switch n := n.(type) {
	case *ast.BracketText:
		BracketText(n)
	case *ast.Extend:
		Extend(n)
	case *ast.Scope:
		Scope(n)
	default:
		panic(fmt.Sprintf("ComponentBody: unknown variant %T: please rerun go generate", n))
	}
}

func ComponentBodyR[T any](n ast.ComponentBody,
	BracketText func(*ast.BracketText) T,
	Extend func(*ast.Extend) T,
	Scope func(*ast.Scope) T,
) T {
	switch n := n.(type) {
	case *ast.BracketText:
		return BracketText(n)
	case *ast.Extend:
		return Extend(n)
	case *ast.Scope:
		return Scope(n)
	default:
		panic(fmt.Sprintf("ComponentBody: unknown variant %T: please rerun go generate", n))
	}
}

func ComponentCallBody(n ast.ComponentCallBody,
	DefaultBlockShorthand func(*ast.DefaultBlockShorthand),
	Scope func(*ast.Scope),
) {
	switch n := n.(type) {
	case *ast.DefaultBlockShorthand:
		DefaultBlockShorthand(n)
	case *ast.Scope:
		Scope(n)
	default:
		panic(fmt.Sprintf("ComponentCallBody: unknown variant %T: please rerun go generate", n))
	}
}

func ComponentCallBodyR[T any](n ast.ComponentCallBody,
	DefaultBlockShorthand func(*ast.DefaultBlockShorthand) T,
	Scope func(*ast.Scope) T,
) T {
	switch n := n.(type) {
	case *ast.DefaultBlockShorthand:
		return DefaultBlockShorthand(n)
	case *ast.Scope:
		return Scope(n)
	default:
		panic(fmt.Sprintf("ComponentCallBody: unknown variant %T: please rerun go generate", n))
	}
}

func ContainingElement(n ast.ContainingElement,
	BlockSetterContainingElement func(*ast.BlockSetterContainingElement),
	Element func(*ast.Element),
) {
	switch n := n.(type) {
	case *ast.BlockSetterContainingElement:
		BlockSetterContainingElement(n)
	case *ast.Element:
		Element(n)
	default:
		panic(fmt.Sprintf("ContainingElement: unknown variant %T: please rerun go generate", n))
	}
}

func ContainingElementR[T any](n ast.ContainingElement,
	BlockSetterContainingElement func(*ast.BlockSetterContainingElement) T,
	Element func(*ast.Element) T,
) T {
	switch n := n.(type) {
	case *ast.BlockSetterContainingElement:
		return BlockSetterContainingElement(n)
	case *ast.Element:
		return Element(n)
	default:
		panic(fmt.Sprintf("ContainingElement: unknown variant %T: please rerun go generate", n))
	}
}

func ContentWriter(n ast.ContentWriter,
	Block func(*ast.Block),
	CharacterEscape func(*ast.CharacterEscape),
	CharacterReference func(*ast.CharacterReference),
	ComponentCall func(*ast.ComponentCall),
	Doctype func(*ast.Doctype),
	Element func(*ast.Element),
	ExpressionInterpolation func(*ast.ExpressionInterpolation),
	RawElement func(*ast.RawElement),
	Text func(*ast.Text),
) {
	switch n := n.(type) {
	case *ast.Block:
		Block(n)
	case *ast.CharacterEscape:
		CharacterEscape(n)
	case *ast.CharacterReference:
		CharacterReference(n)
	case *ast.ComponentCall:
		ComponentCall(n)
	case *ast.Doctype:
		Doctype(n)
	case *ast.Element:
		Element(n)
	case *ast.ExpressionInterpolation:
		ExpressionInterpolation(n)
	case *ast.RawElement:
		RawElement(n)
	case *ast.Text:
		Text(n)
	default:
		panic(fmt.Sprintf("ContentWriter: unknown variant %T: please rerun go generate", n))
	}
}

func ContentWriterR[T any](n ast.ContentWriter,
	Block func(*ast.Block) T,
	CharacterEscape func(*ast.CharacterEscape) T,
	CharacterReference func(*ast.CharacterReference) T,
	ComponentCall func(*ast.ComponentCall) T,
	Doctype func(*ast.Doctype) T,
	Element func(*ast.Element) T,
	ExpressionInterpolation func(*ast.ExpressionInterpolation) T,
	RawElement func(*ast.RawElement) T,
	Text func(*ast.Text) T,
) T {
	switch n := n.(type) {
	case *ast.Block:
		return Block(n)
	case *ast.CharacterEscape:
		return CharacterEscape(n)
	case *ast.CharacterReference:
		return CharacterReference(n)
	case *ast.ComponentCall:
		return ComponentCall(n)
	case *ast.Doctype:
		return Doctype(n)
	case *ast.Element:
		return Element(n)
	case *ast.ExpressionInterpolation:
		return ExpressionInterpolation(n)
	case *ast.RawElement:
		return RawElement(n)
	case *ast.Text:
		return Text(n)
	default:
		panic(fmt.Sprintf("ContentWriter: unknown variant %T: please rerun go generate", n))
	}
}

func ElementSelector(n ast.ElementSelector,
	ListElementSelector func(*ast.ListElementSelector),
	WildcardElementSelector func(*ast.WildcardElementSelector),
) {
	switch n := n.(type) {
	case *ast.ListElementSelector:
		ListElementSelector(n)
	case *ast.WildcardElementSelector:
		WildcardElementSelector(n)
	default:
		panic(fmt.Sprintf("ElementSelector: unknown variant %T: please rerun go generate", n))
	}
}

func ElementSelectorR[T any](n ast.ElementSelector,
	ListElementSelector func(*ast.ListElementSelector) T,
	WildcardElementSelector func(*ast.WildcardElementSelector) T,
) T {
	switch n := n.(type) {
	case *ast.ListElementSelector:
		return ListElementSelector(n)
	case *ast.WildcardElementSelector:
		return WildcardElementSelector(n)
	default:
		panic(fmt.Sprintf("ElementSelector: unknown variant %T: please rerun go generate", n))
	}
}

func ElementType(n ast.ElementType,
	AliasElementType func(*ast.AliasElementType),
	BasicElementType func(*ast.BasicElementType),
) {
	switch n := n.(type) {
	case *ast.AliasElementType:
		AliasElementType(n)
	case *ast.BasicElementType:
		BasicElementType(n)
	default:
		panic(fmt.Sprintf("ElementType: unknown variant %T: please rerun go generate", n))
	}
}

func ElementTypeR[T any](n ast.ElementType,
	AliasElementType func(*ast.AliasElementType) T,
	BasicElementType func(*ast.BasicElementType) T,
) T {
	switch n := n.(type) {
	case *ast.AliasElementType:
		return AliasElementType(n)
	case *ast.BasicElementType:
		return BasicElementType(n)
	default:
		panic(fmt.Sprintf("ElementType: unknown variant %T: please rerun go generate", n))
	}
}

func ElementWriter(n ast.ElementWriter,
	ComponentCall func(*ast.ComponentCall),
	Doctype func(*ast.Doctype),
	Element func(*ast.Element),
) {
	switch n := n.(type) {
	case *ast.ComponentCall:
		ComponentCall(n)
	case *ast.Doctype:
		Doctype(n)
	case *ast.Element:
		Element(n)
	default:
		panic(fmt.Sprintf("ElementWriter: unknown variant %T: please rerun go generate", n))
	}
}

func ElementWriterR[T any](n ast.ElementWriter,
	ComponentCall func(*ast.ComponentCall) T,
	Doctype func(*ast.Doctype) T,
	Element func(*ast.Element) T,
) T {
	switch n := n.(type) {
	case *ast.ComponentCall:
		return ComponentCall(n)
	case *ast.Doctype:
		return Doctype(n)
	case *ast.Element:
		return Element(n)
	default:
		panic(fmt.Sprintf("ElementWriter: unknown variant %T: please rerun go generate", n))
	}
}

func ForHeader(n ast.ForHeader,
	ForClauseHeader func(*ast.ForClauseHeader),
	ForConditionHeader func(*ast.ForConditionHeader),
	ForRangeHeader func(*ast.ForRangeHeader),
) {
	switch n := n.(type) {
	case *ast.ForClauseHeader:
		ForClauseHeader(n)
	case *ast.ForConditionHeader:
		ForConditionHeader(n)
	case *ast.ForRangeHeader:
		ForRangeHeader(n)
	default:
		panic(fmt.Sprintf("ForHeader: unknown variant %T: please rerun go generate", n))
	}
}

func ForHeaderR[T any](n ast.ForHeader,
	ForClauseHeader func(*ast.ForClauseHeader) T,
	ForConditionHeader func(*ast.ForConditionHeader) T,
	ForRangeHeader func(*ast.ForRangeHeader) T,
) T {
	switch n := n.(type) {
	case *ast.ForClauseHeader:
		return ForClauseHeader(n)
	case *ast.ForConditionHeader:
		return ForConditionHeader(n)
	case *ast.ForRangeHeader:
		return ForRangeHeader(n)
	default:
		panic(fmt.Sprintf("ForHeader: unknown variant %T: please rerun go generate", n))
	}
}

func FullIdentifier(n ast.FullIdentifier,
	Identifier func(*ast.Identifier),
	QualifiedIdentifier func(*ast.QualifiedIdentifier),
) {
	switch n := n.(type) {
	case *ast.Identifier:
		Identifier(n)
	case *ast.QualifiedIdentifier:
		QualifiedIdentifier(n)
	default:
		panic(fmt.Sprintf("FullIdentifier: unknown variant %T: please rerun go generate", n))
	}
}

func FullIdentifierR[T any](n ast.FullIdentifier,
	Identifier func(*ast.Identifier) T,
	QualifiedIdentifier func(*ast.QualifiedIdentifier) T,
) T {
	switch n := n.(type) {
	case *ast.Identifier:
		return Identifier(n)
	case *ast.QualifiedIdentifier:
		return QualifiedIdentifier(n)
	default:
		panic(fmt.Sprintf("FullIdentifier: unknown variant %T: please rerun go generate", n))
	}
}

func Interpolation(n ast.Interpolation,
	BadInterpolation func(*ast.BadInterpolation),
	CharacterEscape func(*ast.CharacterEscape),
	CharacterReference func(*ast.CharacterReference),
	ComponentCallInterpolation func(*ast.ComponentCallInterpolation),
	ExpressionInterpolation func(*ast.ExpressionInterpolation),
	ModeSwitch func(*ast.ModeSwitch),
) {
	switch n := n.(type) {
	case *ast.BadInterpolation:
		BadInterpolation(n)
	case *ast.CharacterEscape:
		CharacterEscape(n)
	case *ast.CharacterReference:
		CharacterReference(n)
	case *ast.ComponentCallInterpolation:
		ComponentCallInterpolation(n)
	case *ast.ExpressionInterpolation:
		ExpressionInterpolation(n)
	case *ast.ModeSwitch:
		ModeSwitch(n)
	default:
		panic(fmt.Sprintf("Interpolation: unknown variant %T: please rerun go generate", n))
	}
}

func InterpolationR[T any](n ast.Interpolation,
	BadInterpolation func(*ast.BadInterpolation) T,
	CharacterEscape func(*ast.CharacterEscape) T,
	CharacterReference func(*ast.CharacterReference) T,
	ComponentCallInterpolation func(*ast.ComponentCallInterpolation) T,
	ExpressionInterpolation func(*ast.ExpressionInterpolation) T,
	ModeSwitch func(*ast.ModeSwitch) T,
) T {
	switch n := n.(type) {
	case *ast.BadInterpolation:
		return BadInterpolation(n)
	case *ast.CharacterEscape:
		return CharacterEscape(n)
	case *ast.CharacterReference:
		return CharacterReference(n)
	case *ast.ComponentCallInterpolation:
		return ComponentCallInterpolation(n)
	case *ast.ExpressionInterpolation:
		return ExpressionInterpolation(n)
	case *ast.ModeSwitch:
		return ModeSwitch(n)
	default:
		panic(fmt.Sprintf("Interpolation: unknown variant %T: please rerun go generate", n))
	}
}

func Node(n ast.Node,
	AliasElementType func(*ast.AliasElementType),
	And func(*ast.And),
	AndPlaceholder func(*ast.AndPlaceholder),
	AndPlaceholderAttributeReceiver func(*ast.AndPlaceholderAttributeReceiver),
	Arguments func(*ast.Arguments),
	ArrowBlock func(*ast.ArrowBlock),
	Assignment func(*ast.Assignment),
	AttributeDefinition func(*ast.AttributeDefinition),
	AttributeName func(*ast.AttributeName),
	AttributeReference func(*ast.AttributeReference),
	AttributeRule func(*ast.AttributeRule),
	AttributeRuleset func(*ast.AttributeRuleset),
	AttributeSpec func(*ast.AttributeSpec),
	AttributeType func(*ast.AttributeType),
	AttributeTypeName func(*ast.AttributeTypeName),
	BadInterpolation func(*ast.BadInterpolation),
	BadNode func(*ast.BadNode),
	BasicAttributeSelector func(*ast.BasicAttributeSelector),
	BasicElementType func(*ast.BasicElementType),
	Block func(*ast.Block),
	BlockFunction func(*ast.BlockFunction),
	BlockSetterAttributeInhibitor func(*ast.BlockSetterAttributeInhibitor),
	BlockSetterContainingElement func(*ast.BlockSetterContainingElement),
	BracketText func(*ast.BracketText),
	Break func(*ast.Break),
	Case func(*ast.Case),
	CharacterEscape func(*ast.CharacterEscape),
	CharacterReference func(*ast.CharacterReference),
	ClassShorthand func(*ast.ClassShorthand),
	Code func(ast.Code),
	Comment func(*ast.Comment),
	CommentGroup func(ast.CommentGroup),
	Component func(*ast.Component),
	ComponentArgument func(*ast.ComponentArgument),
	ComponentCall func(*ast.ComponentCall),
	ComponentCallHeader func(*ast.ComponentCallHeader),
	ComponentCallInterpolation func(*ast.ComponentCallInterpolation),
	ComponentHeader func(*ast.ComponentHeader),
	ComponentParameter func(*ast.ComponentParameter),
	ComponentParameters func(*ast.ComponentParameters),
	Conditional func(*ast.Conditional),
	ConstDeclaration func(*ast.ConstDeclaration),
	ConstSpec func(*ast.ConstSpec),
	Continue func(*ast.Continue),
	DefaultBlockShorthand func(*ast.DefaultBlockShorthand),
	Defer func(*ast.Defer),
	Doctype func(*ast.Doctype),
	Element func(*ast.Element),
	ElementDefinition func(*ast.ElementDefinition),
	ElementHeader func(*ast.ElementHeader),
	ElementName func(*ast.ElementName),
	ElementReference func(*ast.ElementReference),
	ElementSpec func(*ast.ElementSpec),
	ElementTypeName func(*ast.ElementTypeName),
	Else func(*ast.Else),
	ElseIf func(*ast.ElseIf),
	ExplicitCodeLine func(*ast.ExplicitCodeLine),
	Expression func(*ast.Expression),
	ExpressionAttributeValue func(*ast.ExpressionAttributeValue),
	ExpressionInterpolation func(*ast.ExpressionInterpolation),
	Extend func(*ast.Extend),
	Fallthrough func(*ast.Fallthrough),
	File func(*ast.File),
	For func(*ast.For),
	ForClauseHeader func(*ast.ForClauseHeader),
	ForConditionHeader func(*ast.ForConditionHeader),
	ForRangeHeader func(*ast.ForRangeHeader),
	GoCode func(*ast.GoCode),
	IDShorthand func(*ast.IDShorthand),
	Identifier func(*ast.Identifier),
	If func(*ast.If),
	IfHeader func(*ast.IfHeader),
	ImplicitCodeLine func(*ast.ImplicitCodeLine),
	Import func(*ast.Import),
	ImportSpec func(*ast.ImportSpec),
	IncDec func(*ast.IncDec),
	Label func(*ast.Label),
	ListElementSelector func(*ast.ListElementSelector),
	ModeSwitch func(*ast.ModeSwitch),
	NamedAttribute func(*ast.NamedAttribute),
	NamedType func(*ast.NamedType),
	PackageDirective func(*ast.PackageDirective),
	QualifiedIdentifier func(*ast.QualifiedIdentifier),
	RawElement func(*ast.RawElement),
	RegexpAttributeSelector func(*ast.RegexpAttributeSelector),
	Return func(*ast.Return),
	Scope func(*ast.Scope),
	ShortVarDeclaration func(*ast.ShortVarDeclaration),
	Shorthand func(ast.Shorthand),
	ShorthandInterpolation func(*ast.ShorthandInterpolation),
	ShorthandText func(*ast.ShorthandText),
	SimpleStatement func(*ast.SimpleStatement),
	Statement func(*ast.Statement),
	String func(*ast.String),
	StringText func(*ast.StringText),
	Switch func(*ast.Switch),
	Ternary func(*ast.Ternary),
	Text func(*ast.Text),
	TextBlock func(ast.TextBlock),
	TextLine func(ast.TextLine),
	TopLevel func(ast.TopLevel),
	Type func(*ast.Type),
	TypeArguments func(*ast.TypeArguments),
	TypeConstraint func(*ast.TypeConstraint),
	TypeParameter func(*ast.TypeParameter),
	TypeParameters func(*ast.TypeParameters),
	TypedAttributeValue func(*ast.TypedAttributeValue),
	UnderlyingParam func(*ast.UnderlyingParam),
	VarDeclaration func(*ast.VarDeclaration),
	VarSpec func(*ast.VarSpec),
	WildcardElementSelector func(*ast.WildcardElementSelector),
	With func(*ast.With),
	ZCIndexExpression func(*ast.ZCIndexExpression),
	ZCParenExpression func(*ast.ZCParenExpression),
	ZCSelectorExpression func(*ast.ZCSelectorExpression),
	ZCTypeAssertionExpression func(*ast.ZCTypeAssertionExpression),
	ZeroCoalescing func(*ast.ZeroCoalescing),
	ZeroCoalescingAssignment func(*ast.ZeroCoalescingAssignment),
) {
	switch n := n.(type) {
	case *ast.AliasElementType:
		AliasElementType(n)
	case *ast.And:
		And(n)
	case *ast.AndPlaceholder:
		AndPlaceholder(n)
	case *ast.AndPlaceholderAttributeReceiver:
		AndPlaceholderAttributeReceiver(n)
	case *ast.Arguments:
		Arguments(n)
	case *ast.ArrowBlock:
		ArrowBlock(n)
	case *ast.Assignment:
		Assignment(n)
	case *ast.AttributeDefinition:
		AttributeDefinition(n)
	case *ast.AttributeName:
		AttributeName(n)
	case *ast.AttributeReference:
		AttributeReference(n)
	case *ast.AttributeRule:
		AttributeRule(n)
	case *ast.AttributeRuleset:
		AttributeRuleset(n)
	case *ast.AttributeSpec:
		AttributeSpec(n)
	case *ast.AttributeType:
		AttributeType(n)
	case *ast.AttributeTypeName:
		AttributeTypeName(n)
	case *ast.BadInterpolation:
		BadInterpolation(n)
	case *ast.BadNode:
		BadNode(n)
	case *ast.BasicAttributeSelector:
		BasicAttributeSelector(n)
	case *ast.BasicElementType:
		BasicElementType(n)
	case *ast.Block:
		Block(n)
	case *ast.BlockFunction:
		BlockFunction(n)
	case *ast.BlockSetterAttributeInhibitor:
		BlockSetterAttributeInhibitor(n)
	case *ast.BlockSetterContainingElement:
		BlockSetterContainingElement(n)
	case *ast.BracketText:
		BracketText(n)
	case *ast.Break:
		Break(n)
	case *ast.Case:
		Case(n)
	case *ast.CharacterEscape:
		CharacterEscape(n)
	case *ast.CharacterReference:
		CharacterReference(n)
	case *ast.ClassShorthand:
		ClassShorthand(n)
	case ast.Code:
		Code(n)
	case *ast.Comment:
		Comment(n)
	case ast.CommentGroup:
		CommentGroup(n)
	case *ast.Component:
		Component(n)
	case *ast.ComponentArgument:
		ComponentArgument(n)
	case *ast.ComponentCall:
		ComponentCall(n)
	case *ast.ComponentCallHeader:
		ComponentCallHeader(n)
	case *ast.ComponentCallInterpolation:
		ComponentCallInterpolation(n)
	case *ast.ComponentHeader:
		ComponentHeader(n)
	case *ast.ComponentParameter:
		ComponentParameter(n)
	case *ast.ComponentParameters:
		ComponentParameters(n)
	case *ast.Conditional:
		Conditional(n)
	case *ast.ConstDeclaration:
		ConstDeclaration(n)
	case *ast.ConstSpec:
		ConstSpec(n)
	case *ast.Continue:
		Continue(n)
	case *ast.DefaultBlockShorthand:
		DefaultBlockShorthand(n)
	case *ast.Defer:
		Defer(n)
	case *ast.Doctype:
		Doctype(n)
	case *ast.Element:
		Element(n)
	case *ast.ElementDefinition:
		ElementDefinition(n)
	case *ast.ElementHeader:
		ElementHeader(n)
	case *ast.ElementName:
		ElementName(n)
	case *ast.ElementReference:
		ElementReference(n)
	case *ast.ElementSpec:
		ElementSpec(n)
	case *ast.ElementTypeName:
		ElementTypeName(n)
	case *ast.Else:
		Else(n)
	case *ast.ElseIf:
		ElseIf(n)
	case *ast.ExplicitCodeLine:
		ExplicitCodeLine(n)
	case *ast.Expression:
		Expression(n)
	case *ast.ExpressionAttributeValue:
		ExpressionAttributeValue(n)
	case *ast.ExpressionInterpolation:
		ExpressionInterpolation(n)
	case *ast.Extend:
		Extend(n)
	case *ast.Fallthrough:
		Fallthrough(n)
	case *ast.File:
		File(n)
	case *ast.For:
		For(n)
	case *ast.ForClauseHeader:
		ForClauseHeader(n)
	case *ast.ForConditionHeader:
		ForConditionHeader(n)
	case *ast.ForRangeHeader:
		ForRangeHeader(n)
	case *ast.GoCode:
		GoCode(n)
	case *ast.IDShorthand:
		IDShorthand(n)
	case *ast.Identifier:
		Identifier(n)
	case *ast.If:
		If(n)
	case *ast.IfHeader:
		IfHeader(n)
	case *ast.ImplicitCodeLine:
		ImplicitCodeLine(n)
	case *ast.Import:
		Import(n)
	case *ast.ImportSpec:
		ImportSpec(n)
	case *ast.IncDec:
		IncDec(n)
	case *ast.Label:
		Label(n)
	case *ast.ListElementSelector:
		ListElementSelector(n)
	case *ast.ModeSwitch:
		ModeSwitch(n)
	case *ast.NamedAttribute:
		NamedAttribute(n)
	case *ast.NamedType:
		NamedType(n)
	case *ast.PackageDirective:
		PackageDirective(n)
	case *ast.QualifiedIdentifier:
		QualifiedIdentifier(n)
	case *ast.RawElement:
		RawElement(n)
	case *ast.RegexpAttributeSelector:
		RegexpAttributeSelector(n)
	case *ast.Return:
		Return(n)
	case *ast.Scope:
		Scope(n)
	case *ast.ShortVarDeclaration:
		ShortVarDeclaration(n)
	case ast.Shorthand:
		Shorthand(n)
	case *ast.ShorthandInterpolation:
		ShorthandInterpolation(n)
	case *ast.ShorthandText:
		ShorthandText(n)
	case *ast.SimpleStatement:
		SimpleStatement(n)
	case *ast.Statement:
		Statement(n)
	case *ast.String:
		String(n)
	case *ast.StringText:
		StringText(n)
	case *ast.Switch:
		Switch(n)
	case *ast.Ternary:
		Ternary(n)
	case *ast.Text:
		Text(n)
	case ast.TextBlock:
		TextBlock(n)
	case ast.TextLine:
		TextLine(n)
	case ast.TopLevel:
		TopLevel(n)
	case *ast.Type:
		Type(n)
	case *ast.TypeArguments:
		TypeArguments(n)
	case *ast.TypeConstraint:
		TypeConstraint(n)
	case *ast.TypeParameter:
		TypeParameter(n)
	case *ast.TypeParameters:
		TypeParameters(n)
	case *ast.TypedAttributeValue:
		TypedAttributeValue(n)
	case *ast.UnderlyingParam:
		UnderlyingParam(n)
	case *ast.VarDeclaration:
		VarDeclaration(n)
	case *ast.VarSpec:
		VarSpec(n)
	case *ast.WildcardElementSelector:
		WildcardElementSelector(n)
	case *ast.With:
		With(n)
	case *ast.ZCIndexExpression:
		ZCIndexExpression(n)
	case *ast.ZCParenExpression:
		ZCParenExpression(n)
	case *ast.ZCSelectorExpression:
		ZCSelectorExpression(n)
	case *ast.ZCTypeAssertionExpression:
		ZCTypeAssertionExpression(n)
	case *ast.ZeroCoalescing:
		ZeroCoalescing(n)
	case *ast.ZeroCoalescingAssignment:
		ZeroCoalescingAssignment(n)
	default:
		panic(fmt.Sprintf("Node: unknown variant %T: please rerun go generate", n))
	}
}

func NodeR[T any](n ast.Node,
	AliasElementType func(*ast.AliasElementType) T,
	And func(*ast.And) T,
	AndPlaceholder func(*ast.AndPlaceholder) T,
	AndPlaceholderAttributeReceiver func(*ast.AndPlaceholderAttributeReceiver) T,
	Arguments func(*ast.Arguments) T,
	ArrowBlock func(*ast.ArrowBlock) T,
	Assignment func(*ast.Assignment) T,
	AttributeDefinition func(*ast.AttributeDefinition) T,
	AttributeName func(*ast.AttributeName) T,
	AttributeReference func(*ast.AttributeReference) T,
	AttributeRule func(*ast.AttributeRule) T,
	AttributeRuleset func(*ast.AttributeRuleset) T,
	AttributeSpec func(*ast.AttributeSpec) T,
	AttributeType func(*ast.AttributeType) T,
	AttributeTypeName func(*ast.AttributeTypeName) T,
	BadInterpolation func(*ast.BadInterpolation) T,
	BadNode func(*ast.BadNode) T,
	BasicAttributeSelector func(*ast.BasicAttributeSelector) T,
	BasicElementType func(*ast.BasicElementType) T,
	Block func(*ast.Block) T,
	BlockFunction func(*ast.BlockFunction) T,
	BlockSetterAttributeInhibitor func(*ast.BlockSetterAttributeInhibitor) T,
	BlockSetterContainingElement func(*ast.BlockSetterContainingElement) T,
	BracketText func(*ast.BracketText) T,
	Break func(*ast.Break) T,
	Case func(*ast.Case) T,
	CharacterEscape func(*ast.CharacterEscape) T,
	CharacterReference func(*ast.CharacterReference) T,
	ClassShorthand func(*ast.ClassShorthand) T,
	Code func(ast.Code) T,
	Comment func(*ast.Comment) T,
	CommentGroup func(ast.CommentGroup) T,
	Component func(*ast.Component) T,
	ComponentArgument func(*ast.ComponentArgument) T,
	ComponentCall func(*ast.ComponentCall) T,
	ComponentCallHeader func(*ast.ComponentCallHeader) T,
	ComponentCallInterpolation func(*ast.ComponentCallInterpolation) T,
	ComponentHeader func(*ast.ComponentHeader) T,
	ComponentParameter func(*ast.ComponentParameter) T,
	ComponentParameters func(*ast.ComponentParameters) T,
	Conditional func(*ast.Conditional) T,
	ConstDeclaration func(*ast.ConstDeclaration) T,
	ConstSpec func(*ast.ConstSpec) T,
	Continue func(*ast.Continue) T,
	DefaultBlockShorthand func(*ast.DefaultBlockShorthand) T,
	Defer func(*ast.Defer) T,
	Doctype func(*ast.Doctype) T,
	Element func(*ast.Element) T,
	ElementDefinition func(*ast.ElementDefinition) T,
	ElementHeader func(*ast.ElementHeader) T,
	ElementName func(*ast.ElementName) T,
	ElementReference func(*ast.ElementReference) T,
	ElementSpec func(*ast.ElementSpec) T,
	ElementTypeName func(*ast.ElementTypeName) T,
	Else func(*ast.Else) T,
	ElseIf func(*ast.ElseIf) T,
	ExplicitCodeLine func(*ast.ExplicitCodeLine) T,
	Expression func(*ast.Expression) T,
	ExpressionAttributeValue func(*ast.ExpressionAttributeValue) T,
	ExpressionInterpolation func(*ast.ExpressionInterpolation) T,
	Extend func(*ast.Extend) T,
	Fallthrough func(*ast.Fallthrough) T,
	File func(*ast.File) T,
	For func(*ast.For) T,
	ForClauseHeader func(*ast.ForClauseHeader) T,
	ForConditionHeader func(*ast.ForConditionHeader) T,
	ForRangeHeader func(*ast.ForRangeHeader) T,
	GoCode func(*ast.GoCode) T,
	IDShorthand func(*ast.IDShorthand) T,
	Identifier func(*ast.Identifier) T,
	If func(*ast.If) T,
	IfHeader func(*ast.IfHeader) T,
	ImplicitCodeLine func(*ast.ImplicitCodeLine) T,
	Import func(*ast.Import) T,
	ImportSpec func(*ast.ImportSpec) T,
	IncDec func(*ast.IncDec) T,
	Label func(*ast.Label) T,
	ListElementSelector func(*ast.ListElementSelector) T,
	ModeSwitch func(*ast.ModeSwitch) T,
	NamedAttribute func(*ast.NamedAttribute) T,
	NamedType func(*ast.NamedType) T,
	PackageDirective func(*ast.PackageDirective) T,
	QualifiedIdentifier func(*ast.QualifiedIdentifier) T,
	RawElement func(*ast.RawElement) T,
	RegexpAttributeSelector func(*ast.RegexpAttributeSelector) T,
	Return func(*ast.Return) T,
	Scope func(*ast.Scope) T,
	ShortVarDeclaration func(*ast.ShortVarDeclaration) T,
	Shorthand func(ast.Shorthand) T,
	ShorthandInterpolation func(*ast.ShorthandInterpolation) T,
	ShorthandText func(*ast.ShorthandText) T,
	SimpleStatement func(*ast.SimpleStatement) T,
	Statement func(*ast.Statement) T,
	String func(*ast.String) T,
	StringText func(*ast.StringText) T,
	Switch func(*ast.Switch) T,
	Ternary func(*ast.Ternary) T,
	Text func(*ast.Text) T,
	TextBlock func(ast.TextBlock) T,
	TextLine func(ast.TextLine) T,
	TopLevel func(ast.TopLevel) T,
	Type func(*ast.Type) T,
	TypeArguments func(*ast.TypeArguments) T,
	TypeConstraint func(*ast.TypeConstraint) T,
	TypeParameter func(*ast.TypeParameter) T,
	TypeParameters func(*ast.TypeParameters) T,
	TypedAttributeValue func(*ast.TypedAttributeValue) T,
	UnderlyingParam func(*ast.UnderlyingParam) T,
	VarDeclaration func(*ast.VarDeclaration) T,
	VarSpec func(*ast.VarSpec) T,
	WildcardElementSelector func(*ast.WildcardElementSelector) T,
	With func(*ast.With) T,
	ZCIndexExpression func(*ast.ZCIndexExpression) T,
	ZCParenExpression func(*ast.ZCParenExpression) T,
	ZCSelectorExpression func(*ast.ZCSelectorExpression) T,
	ZCTypeAssertionExpression func(*ast.ZCTypeAssertionExpression) T,
	ZeroCoalescing func(*ast.ZeroCoalescing) T,
	ZeroCoalescingAssignment func(*ast.ZeroCoalescingAssignment) T,
) T {
	switch n := n.(type) {
	case *ast.AliasElementType:
		return AliasElementType(n)
	case *ast.And:
		return And(n)
	case *ast.AndPlaceholder:
		return AndPlaceholder(n)
	case *ast.AndPlaceholderAttributeReceiver:
		return AndPlaceholderAttributeReceiver(n)
	case *ast.Arguments:
		return Arguments(n)
	case *ast.ArrowBlock:
		return ArrowBlock(n)
	case *ast.Assignment:
		return Assignment(n)
	case *ast.AttributeDefinition:
		return AttributeDefinition(n)
	case *ast.AttributeName:
		return AttributeName(n)
	case *ast.AttributeReference:
		return AttributeReference(n)
	case *ast.AttributeRule:
		return AttributeRule(n)
	case *ast.AttributeRuleset:
		return AttributeRuleset(n)
	case *ast.AttributeSpec:
		return AttributeSpec(n)
	case *ast.AttributeType:
		return AttributeType(n)
	case *ast.AttributeTypeName:
		return AttributeTypeName(n)
	case *ast.BadInterpolation:
		return BadInterpolation(n)
	case *ast.BadNode:
		return BadNode(n)
	case *ast.BasicAttributeSelector:
		return BasicAttributeSelector(n)
	case *ast.BasicElementType:
		return BasicElementType(n)
	case *ast.Block:
		return Block(n)
	case *ast.BlockFunction:
		return BlockFunction(n)
	case *ast.BlockSetterAttributeInhibitor:
		return BlockSetterAttributeInhibitor(n)
	case *ast.BlockSetterContainingElement:
		return BlockSetterContainingElement(n)
	case *ast.BracketText:
		return BracketText(n)
	case *ast.Break:
		return Break(n)
	case *ast.Case:
		return Case(n)
	case *ast.CharacterEscape:
		return CharacterEscape(n)
	case *ast.CharacterReference:
		return CharacterReference(n)
	case *ast.ClassShorthand:
		return ClassShorthand(n)
	case ast.Code:
		return Code(n)
	case *ast.Comment:
		return Comment(n)
	case ast.CommentGroup:
		return CommentGroup(n)
	case *ast.Component:
		return Component(n)
	case *ast.ComponentArgument:
		return ComponentArgument(n)
	case *ast.ComponentCall:
		return ComponentCall(n)
	case *ast.ComponentCallHeader:
		return ComponentCallHeader(n)
	case *ast.ComponentCallInterpolation:
		return ComponentCallInterpolation(n)
	case *ast.ComponentHeader:
		return ComponentHeader(n)
	case *ast.ComponentParameter:
		return ComponentParameter(n)
	case *ast.ComponentParameters:
		return ComponentParameters(n)
	case *ast.Conditional:
		return Conditional(n)
	case *ast.ConstDeclaration:
		return ConstDeclaration(n)
	case *ast.ConstSpec:
		return ConstSpec(n)
	case *ast.Continue:
		return Continue(n)
	case *ast.DefaultBlockShorthand:
		return DefaultBlockShorthand(n)
	case *ast.Defer:
		return Defer(n)
	case *ast.Doctype:
		return Doctype(n)
	case *ast.Element:
		return Element(n)
	case *ast.ElementDefinition:
		return ElementDefinition(n)
	case *ast.ElementHeader:
		return ElementHeader(n)
	case *ast.ElementName:
		return ElementName(n)
	case *ast.ElementReference:
		return ElementReference(n)
	case *ast.ElementSpec:
		return ElementSpec(n)
	case *ast.ElementTypeName:
		return ElementTypeName(n)
	case *ast.Else:
		return Else(n)
	case *ast.ElseIf:
		return ElseIf(n)
	case *ast.ExplicitCodeLine:
		return ExplicitCodeLine(n)
	case *ast.Expression:
		return Expression(n)
	case *ast.ExpressionAttributeValue:
		return ExpressionAttributeValue(n)
	case *ast.ExpressionInterpolation:
		return ExpressionInterpolation(n)
	case *ast.Extend:
		return Extend(n)
	case *ast.Fallthrough:
		return Fallthrough(n)
	case *ast.File:
		return File(n)
	case *ast.For:
		return For(n)
	case *ast.ForClauseHeader:
		return ForClauseHeader(n)
	case *ast.ForConditionHeader:
		return ForConditionHeader(n)
	case *ast.ForRangeHeader:
		return ForRangeHeader(n)
	case *ast.GoCode:
		return GoCode(n)
	case *ast.IDShorthand:
		return IDShorthand(n)
	case *ast.Identifier:
		return Identifier(n)
	case *ast.If:
		return If(n)
	case *ast.IfHeader:
		return IfHeader(n)
	case *ast.ImplicitCodeLine:
		return ImplicitCodeLine(n)
	case *ast.Import:
		return Import(n)
	case *ast.ImportSpec:
		return ImportSpec(n)
	case *ast.IncDec:
		return IncDec(n)
	case *ast.Label:
		return Label(n)
	case *ast.ListElementSelector:
		return ListElementSelector(n)
	case *ast.ModeSwitch:
		return ModeSwitch(n)
	case *ast.NamedAttribute:
		return NamedAttribute(n)
	case *ast.NamedType:
		return NamedType(n)
	case *ast.PackageDirective:
		return PackageDirective(n)
	case *ast.QualifiedIdentifier:
		return QualifiedIdentifier(n)
	case *ast.RawElement:
		return RawElement(n)
	case *ast.RegexpAttributeSelector:
		return RegexpAttributeSelector(n)
	case *ast.Return:
		return Return(n)
	case *ast.Scope:
		return Scope(n)
	case *ast.ShortVarDeclaration:
		return ShortVarDeclaration(n)
	case ast.Shorthand:
		return Shorthand(n)
	case *ast.ShorthandInterpolation:
		return ShorthandInterpolation(n)
	case *ast.ShorthandText:
		return ShorthandText(n)
	case *ast.SimpleStatement:
		return SimpleStatement(n)
	case *ast.Statement:
		return Statement(n)
	case *ast.String:
		return String(n)
	case *ast.StringText:
		return StringText(n)
	case *ast.Switch:
		return Switch(n)
	case *ast.Ternary:
		return Ternary(n)
	case *ast.Text:
		return Text(n)
	case ast.TextBlock:
		return TextBlock(n)
	case ast.TextLine:
		return TextLine(n)
	case ast.TopLevel:
		return TopLevel(n)
	case *ast.Type:
		return Type(n)
	case *ast.TypeArguments:
		return TypeArguments(n)
	case *ast.TypeConstraint:
		return TypeConstraint(n)
	case *ast.TypeParameter:
		return TypeParameter(n)
	case *ast.TypeParameters:
		return TypeParameters(n)
	case *ast.TypedAttributeValue:
		return TypedAttributeValue(n)
	case *ast.UnderlyingParam:
		return UnderlyingParam(n)
	case *ast.VarDeclaration:
		return VarDeclaration(n)
	case *ast.VarSpec:
		return VarSpec(n)
	case *ast.WildcardElementSelector:
		return WildcardElementSelector(n)
	case *ast.With:
		return With(n)
	case *ast.ZCIndexExpression:
		return ZCIndexExpression(n)
	case *ast.ZCParenExpression:
		return ZCParenExpression(n)
	case *ast.ZCSelectorExpression:
		return ZCSelectorExpression(n)
	case *ast.ZCTypeAssertionExpression:
		return ZCTypeAssertionExpression(n)
	case *ast.ZeroCoalescing:
		return ZeroCoalescing(n)
	case *ast.ZeroCoalescingAssignment:
		return ZeroCoalescingAssignment(n)
	default:
		panic(fmt.Sprintf("Node: unknown variant %T: please rerun go generate", n))
	}
}

func ParsedSimpleStatement(n ast.ParsedSimpleStatement,
	Assignment func(*ast.Assignment),
	IncDec func(*ast.IncDec),
	ShortVarDeclaration func(*ast.ShortVarDeclaration),
	ZeroCoalescingAssignment func(*ast.ZeroCoalescingAssignment),
) {
	switch n := n.(type) {
	case *ast.Assignment:
		Assignment(n)
	case *ast.IncDec:
		IncDec(n)
	case *ast.ShortVarDeclaration:
		ShortVarDeclaration(n)
	case *ast.ZeroCoalescingAssignment:
		ZeroCoalescingAssignment(n)
	default:
		panic(fmt.Sprintf("ParsedSimpleStatement: unknown variant %T: please rerun go generate", n))
	}
}

func ParsedSimpleStatementR[T any](n ast.ParsedSimpleStatement,
	Assignment func(*ast.Assignment) T,
	IncDec func(*ast.IncDec) T,
	ShortVarDeclaration func(*ast.ShortVarDeclaration) T,
	ZeroCoalescingAssignment func(*ast.ZeroCoalescingAssignment) T,
) T {
	switch n := n.(type) {
	case *ast.Assignment:
		return Assignment(n)
	case *ast.IncDec:
		return IncDec(n)
	case *ast.ShortVarDeclaration:
		return ShortVarDeclaration(n)
	case *ast.ZeroCoalescingAssignment:
		return ZeroCoalescingAssignment(n)
	default:
		panic(fmt.Sprintf("ParsedSimpleStatement: unknown variant %T: please rerun go generate", n))
	}
}

func ParsedStatement(n ast.ParsedStatement,
	Assignment func(*ast.Assignment),
	Break func(*ast.Break),
	ConstDeclaration func(*ast.ConstDeclaration),
	Continue func(*ast.Continue),
	Defer func(*ast.Defer),
	Fallthrough func(*ast.Fallthrough),
	IncDec func(*ast.IncDec),
	Label func(*ast.Label),
	Return func(*ast.Return),
	ShortVarDeclaration func(*ast.ShortVarDeclaration),
	VarDeclaration func(*ast.VarDeclaration),
	ZeroCoalescingAssignment func(*ast.ZeroCoalescingAssignment),
) {
	switch n := n.(type) {
	case *ast.Assignment:
		Assignment(n)
	case *ast.Break:
		Break(n)
	case *ast.ConstDeclaration:
		ConstDeclaration(n)
	case *ast.Continue:
		Continue(n)
	case *ast.Defer:
		Defer(n)
	case *ast.Fallthrough:
		Fallthrough(n)
	case *ast.IncDec:
		IncDec(n)
	case *ast.Label:
		Label(n)
	case *ast.Return:
		Return(n)
	case *ast.ShortVarDeclaration:
		ShortVarDeclaration(n)
	case *ast.VarDeclaration:
		VarDeclaration(n)
	case *ast.ZeroCoalescingAssignment:
		ZeroCoalescingAssignment(n)
	default:
		panic(fmt.Sprintf("ParsedStatement: unknown variant %T: please rerun go generate", n))
	}
}

func ParsedStatementR[T any](n ast.ParsedStatement,
	Assignment func(*ast.Assignment) T,
	Break func(*ast.Break) T,
	ConstDeclaration func(*ast.ConstDeclaration) T,
	Continue func(*ast.Continue) T,
	Defer func(*ast.Defer) T,
	Fallthrough func(*ast.Fallthrough) T,
	IncDec func(*ast.IncDec) T,
	Label func(*ast.Label) T,
	Return func(*ast.Return) T,
	ShortVarDeclaration func(*ast.ShortVarDeclaration) T,
	VarDeclaration func(*ast.VarDeclaration) T,
	ZeroCoalescingAssignment func(*ast.ZeroCoalescingAssignment) T,
) T {
	switch n := n.(type) {
	case *ast.Assignment:
		return Assignment(n)
	case *ast.Break:
		return Break(n)
	case *ast.ConstDeclaration:
		return ConstDeclaration(n)
	case *ast.Continue:
		return Continue(n)
	case *ast.Defer:
		return Defer(n)
	case *ast.Fallthrough:
		return Fallthrough(n)
	case *ast.IncDec:
		return IncDec(n)
	case *ast.Label:
		return Label(n)
	case *ast.Return:
		return Return(n)
	case *ast.ShortVarDeclaration:
		return ShortVarDeclaration(n)
	case *ast.VarDeclaration:
		return VarDeclaration(n)
	case *ast.ZeroCoalescingAssignment:
		return ZeroCoalescingAssignment(n)
	default:
		panic(fmt.Sprintf("ParsedStatement: unknown variant %T: please rerun go generate", n))
	}
}

func ParsedType(n ast.ParsedType,
	AttributeType func(*ast.AttributeType),
	NamedType func(*ast.NamedType),
) {
	switch n := n.(type) {
	case *ast.AttributeType:
		AttributeType(n)
	case *ast.NamedType:
		NamedType(n)
	default:
		panic(fmt.Sprintf("ParsedType: unknown variant %T: please rerun go generate", n))
	}
}

func ParsedTypeR[T any](n ast.ParsedType,
	AttributeType func(*ast.AttributeType) T,
	NamedType func(*ast.NamedType) T,
) T {
	switch n := n.(type) {
	case *ast.AttributeType:
		return AttributeType(n)
	case *ast.NamedType:
		return NamedType(n)
	default:
		panic(fmt.Sprintf("ParsedType: unknown variant %T: please rerun go generate", n))
	}
}

func ResolvedValue(n file.ResolvedValue,
	BoolExpression func(*file.BoolExpression),
	ConstantBool func(file.ConstantBool),
	Text func(file.Text),
	UndeterminedExpression func(*file.UndeterminedExpression),
) {
	switch n := n.(type) {
	case *file.BoolExpression:
		BoolExpression(n)
	case file.ConstantBool:
		ConstantBool(n)
	case file.Text:
		Text(n)
	case *file.UndeterminedExpression:
		UndeterminedExpression(n)
	default:
		panic(fmt.Sprintf("ResolvedValue: unknown variant %T: please rerun go generate", n))
	}
}

func ResolvedValueR[T any](n file.ResolvedValue,
	BoolExpression func(*file.BoolExpression) T,
	ConstantBool func(file.ConstantBool) T,
	Text func(file.Text) T,
	UndeterminedExpression func(*file.UndeterminedExpression) T,
) T {
	switch n := n.(type) {
	case *file.BoolExpression:
		return BoolExpression(n)
	case file.ConstantBool:
		return ConstantBool(n)
	case file.Text:
		return Text(n)
	case *file.UndeterminedExpression:
		return UndeterminedExpression(n)
	default:
		panic(fmt.Sprintf("ResolvedValue: unknown variant %T: please rerun go generate", n))
	}
}

func ScopeNode(n ast.ScopeNode,
	And func(*ast.And),
	ArrowBlock func(*ast.ArrowBlock),
	BadNode func(*ast.BadNode),
	Block func(*ast.Block),
	ComponentCall func(*ast.ComponentCall),
	Conditional func(*ast.Conditional),
	Doctype func(*ast.Doctype),
	Element func(*ast.Element),
	ExplicitCodeLine func(*ast.ExplicitCodeLine),
	For func(*ast.For),
	ImplicitCodeLine func(*ast.ImplicitCodeLine),
	RawElement func(*ast.RawElement),
	Switch func(*ast.Switch),
	With func(*ast.With),
) {
	switch n := n.(type) {
	case *ast.And:
		And(n)
	case *ast.ArrowBlock:
		ArrowBlock(n)
	case *ast.BadNode:
		BadNode(n)
	case *ast.Block:
		Block(n)
	case *ast.ComponentCall:
		ComponentCall(n)
	case *ast.Conditional:
		Conditional(n)
	case *ast.Doctype:
		Doctype(n)
	case *ast.Element:
		Element(n)
	case *ast.ExplicitCodeLine:
		ExplicitCodeLine(n)
	case *ast.For:
		For(n)
	case *ast.ImplicitCodeLine:
		ImplicitCodeLine(n)
	case *ast.RawElement:
		RawElement(n)
	case *ast.Switch:
		Switch(n)
	case *ast.With:
		With(n)
	default:
		panic(fmt.Sprintf("ScopeNode: unknown variant %T: please rerun go generate", n))
	}
}

func ScopeNodeR[T any](n ast.ScopeNode,
	And func(*ast.And) T,
	ArrowBlock func(*ast.ArrowBlock) T,
	BadNode func(*ast.BadNode) T,
	Block func(*ast.Block) T,
	ComponentCall func(*ast.ComponentCall) T,
	Conditional func(*ast.Conditional) T,
	Doctype func(*ast.Doctype) T,
	Element func(*ast.Element) T,
	ExplicitCodeLine func(*ast.ExplicitCodeLine) T,
	For func(*ast.For) T,
	ImplicitCodeLine func(*ast.ImplicitCodeLine) T,
	RawElement func(*ast.RawElement) T,
	Switch func(*ast.Switch) T,
	With func(*ast.With) T,
) T {
	switch n := n.(type) {
	case *ast.And:
		return And(n)
	case *ast.ArrowBlock:
		return ArrowBlock(n)
	case *ast.BadNode:
		return BadNode(n)
	case *ast.Block:
		return Block(n)
	case *ast.ComponentCall:
		return ComponentCall(n)
	case *ast.Conditional:
		return Conditional(n)
	case *ast.Doctype:
		return Doctype(n)
	case *ast.Element:
		return Element(n)
	case *ast.ExplicitCodeLine:
		return ExplicitCodeLine(n)
	case *ast.For:
		return For(n)
	case *ast.ImplicitCodeLine:
		return ImplicitCodeLine(n)
	case *ast.RawElement:
		return RawElement(n)
	case *ast.Switch:
		return Switch(n)
	case *ast.With:
		return With(n)
	default:
		panic(fmt.Sprintf("ScopeNode: unknown variant %T: please rerun go generate", n))
	}
}

func ShorthandNode(n ast.ShorthandNode,
	ShorthandInterpolation func(*ast.ShorthandInterpolation),
	ShorthandText func(*ast.ShorthandText),
) {
	switch n := n.(type) {
	case *ast.ShorthandInterpolation:
		ShorthandInterpolation(n)
	case *ast.ShorthandText:
		ShorthandText(n)
	default:
		panic(fmt.Sprintf("ShorthandNode: unknown variant %T: please rerun go generate", n))
	}
}

func ShorthandNodeR[T any](n ast.ShorthandNode,
	ShorthandInterpolation func(*ast.ShorthandInterpolation) T,
	ShorthandText func(*ast.ShorthandText) T,
) T {
	switch n := n.(type) {
	case *ast.ShorthandInterpolation:
		return ShorthandInterpolation(n)
	case *ast.ShorthandText:
		return ShorthandText(n)
	default:
		panic(fmt.Sprintf("ShorthandNode: unknown variant %T: please rerun go generate", n))
	}
}

func StringInterpolation(n ast.StringInterpolation,
	BadInterpolation func(*ast.BadInterpolation),
	CharacterEscape func(*ast.CharacterEscape),
	CharacterReference func(*ast.CharacterReference),
	ComponentCallInterpolation func(*ast.ComponentCallInterpolation),
	ExpressionInterpolation func(*ast.ExpressionInterpolation),
) {
	switch n := n.(type) {
	case *ast.BadInterpolation:
		BadInterpolation(n)
	case *ast.CharacterEscape:
		CharacterEscape(n)
	case *ast.CharacterReference:
		CharacterReference(n)
	case *ast.ComponentCallInterpolation:
		ComponentCallInterpolation(n)
	case *ast.ExpressionInterpolation:
		ExpressionInterpolation(n)
	default:
		panic(fmt.Sprintf("StringInterpolation: unknown variant %T: please rerun go generate", n))
	}
}

func StringInterpolationR[T any](n ast.StringInterpolation,
	BadInterpolation func(*ast.BadInterpolation) T,
	CharacterEscape func(*ast.CharacterEscape) T,
	CharacterReference func(*ast.CharacterReference) T,
	ComponentCallInterpolation func(*ast.ComponentCallInterpolation) T,
	ExpressionInterpolation func(*ast.ExpressionInterpolation) T,
) T {
	switch n := n.(type) {
	case *ast.BadInterpolation:
		return BadInterpolation(n)
	case *ast.CharacterEscape:
		return CharacterEscape(n)
	case *ast.CharacterReference:
		return CharacterReference(n)
	case *ast.ComponentCallInterpolation:
		return ComponentCallInterpolation(n)
	case *ast.ExpressionInterpolation:
		return ExpressionInterpolation(n)
	default:
		panic(fmt.Sprintf("StringInterpolation: unknown variant %T: please rerun go generate", n))
	}
}

func StringNode(n ast.StringNode,
	BadInterpolation func(*ast.BadInterpolation),
	CharacterEscape func(*ast.CharacterEscape),
	CharacterReference func(*ast.CharacterReference),
	ComponentCallInterpolation func(*ast.ComponentCallInterpolation),
	ExpressionInterpolation func(*ast.ExpressionInterpolation),
	StringText func(*ast.StringText),
) {
	switch n := n.(type) {
	case *ast.BadInterpolation:
		BadInterpolation(n)
	case *ast.CharacterEscape:
		CharacterEscape(n)
	case *ast.CharacterReference:
		CharacterReference(n)
	case *ast.ComponentCallInterpolation:
		ComponentCallInterpolation(n)
	case *ast.ExpressionInterpolation:
		ExpressionInterpolation(n)
	case *ast.StringText:
		StringText(n)
	default:
		panic(fmt.Sprintf("StringNode: unknown variant %T: please rerun go generate", n))
	}
}

func StringNodeR[T any](n ast.StringNode,
	BadInterpolation func(*ast.BadInterpolation) T,
	CharacterEscape func(*ast.CharacterEscape) T,
	CharacterReference func(*ast.CharacterReference) T,
	ComponentCallInterpolation func(*ast.ComponentCallInterpolation) T,
	ExpressionInterpolation func(*ast.ExpressionInterpolation) T,
	StringText func(*ast.StringText) T,
) T {
	switch n := n.(type) {
	case *ast.BadInterpolation:
		return BadInterpolation(n)
	case *ast.CharacterEscape:
		return CharacterEscape(n)
	case *ast.CharacterReference:
		return CharacterReference(n)
	case *ast.ComponentCallInterpolation:
		return ComponentCallInterpolation(n)
	case *ast.ExpressionInterpolation:
		return ExpressionInterpolation(n)
	case *ast.StringText:
		return StringText(n)
	default:
		panic(fmt.Sprintf("StringNode: unknown variant %T: please rerun go generate", n))
	}
}

func TextInterpolation(n ast.TextInterpolation,
	BadInterpolation func(*ast.BadInterpolation),
	CharacterEscape func(*ast.CharacterEscape),
	CharacterReference func(*ast.CharacterReference),
	ExpressionInterpolation func(*ast.ExpressionInterpolation),
	ModeSwitch func(*ast.ModeSwitch),
) {
	switch n := n.(type) {
	case *ast.BadInterpolation:
		BadInterpolation(n)
	case *ast.CharacterEscape:
		CharacterEscape(n)
	case *ast.CharacterReference:
		CharacterReference(n)
	case *ast.ExpressionInterpolation:
		ExpressionInterpolation(n)
	case *ast.ModeSwitch:
		ModeSwitch(n)
	default:
		panic(fmt.Sprintf("TextInterpolation: unknown variant %T: please rerun go generate", n))
	}
}

func TextInterpolationR[T any](n ast.TextInterpolation,
	BadInterpolation func(*ast.BadInterpolation) T,
	CharacterEscape func(*ast.CharacterEscape) T,
	CharacterReference func(*ast.CharacterReference) T,
	ExpressionInterpolation func(*ast.ExpressionInterpolation) T,
	ModeSwitch func(*ast.ModeSwitch) T,
) T {
	switch n := n.(type) {
	case *ast.BadInterpolation:
		return BadInterpolation(n)
	case *ast.CharacterEscape:
		return CharacterEscape(n)
	case *ast.CharacterReference:
		return CharacterReference(n)
	case *ast.ExpressionInterpolation:
		return ExpressionInterpolation(n)
	case *ast.ModeSwitch:
		return ModeSwitch(n)
	default:
		panic(fmt.Sprintf("TextInterpolation: unknown variant %T: please rerun go generate", n))
	}
}

func TextNode(n ast.TextNode,
	BadInterpolation func(*ast.BadInterpolation),
	CharacterEscape func(*ast.CharacterEscape),
	CharacterReference func(*ast.CharacterReference),
	ExpressionInterpolation func(*ast.ExpressionInterpolation),
	ModeSwitch func(*ast.ModeSwitch),
	Text func(*ast.Text),
) {
	switch n := n.(type) {
	case *ast.BadInterpolation:
		BadInterpolation(n)
	case *ast.CharacterEscape:
		CharacterEscape(n)
	case *ast.CharacterReference:
		CharacterReference(n)
	case *ast.ExpressionInterpolation:
		ExpressionInterpolation(n)
	case *ast.ModeSwitch:
		ModeSwitch(n)
	case *ast.Text:
		Text(n)
	default:
		panic(fmt.Sprintf("TextNode: unknown variant %T: please rerun go generate", n))
	}
}

func TextNodeR[T any](n ast.TextNode,
	BadInterpolation func(*ast.BadInterpolation) T,
	CharacterEscape func(*ast.CharacterEscape) T,
	CharacterReference func(*ast.CharacterReference) T,
	ExpressionInterpolation func(*ast.ExpressionInterpolation) T,
	ModeSwitch func(*ast.ModeSwitch) T,
	Text func(*ast.Text) T,
) T {
	switch n := n.(type) {
	case *ast.BadInterpolation:
		return BadInterpolation(n)
	case *ast.CharacterEscape:
		return CharacterEscape(n)
	case *ast.CharacterReference:
		return CharacterReference(n)
	case *ast.ExpressionInterpolation:
		return ExpressionInterpolation(n)
	case *ast.ModeSwitch:
		return ModeSwitch(n)
	case *ast.Text:
		return Text(n)
	default:
		panic(fmt.Sprintf("TextNode: unknown variant %T: please rerun go generate", n))
	}
}

func TextPart(n file.TextPart,
	ComponentCallPart func(*file.ComponentCallPart),
	ConstantPart func(file.ConstantPart),
	ExpressionPart func(*file.ExpressionPart),
) {
	switch n := n.(type) {
	case *file.ComponentCallPart:
		ComponentCallPart(n)
	case file.ConstantPart:
		ConstantPart(n)
	case *file.ExpressionPart:
		ExpressionPart(n)
	default:
		panic(fmt.Sprintf("TextPart: unknown variant %T: please rerun go generate", n))
	}
}

func TextPartR[T any](n file.TextPart,
	ComponentCallPart func(*file.ComponentCallPart) T,
	ConstantPart func(file.ConstantPart) T,
	ExpressionPart func(*file.ExpressionPart) T,
) T {
	switch n := n.(type) {
	case *file.ComponentCallPart:
		return ComponentCallPart(n)
	case file.ConstantPart:
		return ConstantPart(n)
	case *file.ExpressionPart:
		return ExpressionPart(n)
	default:
		panic(fmt.Sprintf("TextPart: unknown variant %T: please rerun go generate", n))
	}
}

func TopLevelNode(n ast.TopLevelNode,
	AttributeDefinition func(*ast.AttributeDefinition),
	BadNode func(*ast.BadNode),
	Component func(*ast.Component),
	ElementDefinition func(*ast.ElementDefinition),
	ImplicitCodeLine func(*ast.ImplicitCodeLine),
) {
	switch n := n.(type) {
	case *ast.AttributeDefinition:
		AttributeDefinition(n)
	case *ast.BadNode:
		BadNode(n)
	case *ast.Component:
		Component(n)
	case *ast.ElementDefinition:
		ElementDefinition(n)
	case *ast.ImplicitCodeLine:
		ImplicitCodeLine(n)
	default:
		panic(fmt.Sprintf("TopLevelNode: unknown variant %T: please rerun go generate", n))
	}
}

func TopLevelNodeR[T any](n ast.TopLevelNode,
	AttributeDefinition func(*ast.AttributeDefinition) T,
	BadNode func(*ast.BadNode) T,
	Component func(*ast.Component) T,
	ElementDefinition func(*ast.ElementDefinition) T,
	ImplicitCodeLine func(*ast.ImplicitCodeLine) T,
) T {
	switch n := n.(type) {
	case *ast.AttributeDefinition:
		return AttributeDefinition(n)
	case *ast.BadNode:
		return BadNode(n)
	case *ast.Component:
		return Component(n)
	case *ast.ElementDefinition:
		return ElementDefinition(n)
	case *ast.ImplicitCodeLine:
		return ImplicitCodeLine(n)
	default:
		panic(fmt.Sprintf("TopLevelNode: unknown variant %T: please rerun go generate", n))
	}
}

func TypeTerm(n ast.TypeTerm,
	Type func(*ast.Type),
	UnderlyingParam func(*ast.UnderlyingParam),
) {
	switch n := n.(type) {
	case *ast.Type:
		Type(n)
	case *ast.UnderlyingParam:
		UnderlyingParam(n)
	default:
		panic(fmt.Sprintf("TypeTerm: unknown variant %T: please rerun go generate", n))
	}
}

func TypeTermR[T any](n ast.TypeTerm,
	Type func(*ast.Type) T,
	UnderlyingParam func(*ast.UnderlyingParam) T,
) T {
	switch n := n.(type) {
	case *ast.Type:
		return Type(n)
	case *ast.UnderlyingParam:
		return UnderlyingParam(n)
	default:
		panic(fmt.Sprintf("TypeTerm: unknown variant %T: please rerun go generate", n))
	}
}

func ZeroCoalescingNode(n ast.ZeroCoalescingNode,
	ZCIndexExpression func(*ast.ZCIndexExpression),
	ZCParenExpression func(*ast.ZCParenExpression),
	ZCSelectorExpression func(*ast.ZCSelectorExpression),
	ZCTypeAssertionExpression func(*ast.ZCTypeAssertionExpression),
) {
	switch n := n.(type) {
	case *ast.ZCIndexExpression:
		ZCIndexExpression(n)
	case *ast.ZCParenExpression:
		ZCParenExpression(n)
	case *ast.ZCSelectorExpression:
		ZCSelectorExpression(n)
	case *ast.ZCTypeAssertionExpression:
		ZCTypeAssertionExpression(n)
	default:
		panic(fmt.Sprintf("ZeroCoalescingNode: unknown variant %T: please rerun go generate", n))
	}
}

func ZeroCoalescingNodeR[T any](n ast.ZeroCoalescingNode,
	ZCIndexExpression func(*ast.ZCIndexExpression) T,
	ZCParenExpression func(*ast.ZCParenExpression) T,
	ZCSelectorExpression func(*ast.ZCSelectorExpression) T,
	ZCTypeAssertionExpression func(*ast.ZCTypeAssertionExpression) T,
) T {
	switch n := n.(type) {
	case *ast.ZCIndexExpression:
		return ZCIndexExpression(n)
	case *ast.ZCParenExpression:
		return ZCParenExpression(n)
	case *ast.ZCSelectorExpression:
		return ZCSelectorExpression(n)
	case *ast.ZCTypeAssertionExpression:
		return ZCTypeAssertionExpression(n)
	default:
		panic(fmt.Sprintf("ZeroCoalescingNode: unknown variant %T: please rerun go generate", n))
	}
}
