name: Check Generated Files
on: [ push ]

jobs:
  test:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
      - name: Install direnv
        run: |
          curl -sfL https://direnv.net/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Load direnv
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"

      - name: Check If Generated Files Need To Be Regenerated
        run: ./scripts/check_need_regenerate.sh
