name: Check Generated Files
on: [push]

jobs:
  test:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Check If Generated Files Need To Be Regenerated
        run: ./scripts/check_need_regenerate.sh
