name: Code Coverage

on: [push, pull_request]

jobs:
  codecov:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set GOROOT
        run: echo "GOROOT=$(go env GOROOT)" >> $GITHUB_ENV
      - name: Generate General Coverage Report
        run: go test -coverprofile coverage.txt -covermode atomic ./...
      - name: Generate General Coverage Report
        run: go test -coverprofile coverage2.txt -coverpkg github.com/mavolin/corgi/v2/load/... -covermode atomic github.com/mavolin/corgi/v2/examples
      - name: Upload Unit Test Coverage to Codecov
        uses: codecov/codecov-action@v5
