name: Code Coverage
on: [ push, pull_request ]

jobs:
  codecov:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Enter direnv
        uses: .github/actions/enter-direnv
      - name: Cache Go Modules
        uses: actions/setup-go@v6

      - name: Generate Coverage Report
        run: ./scripts/coverprofile.sh coverage.out
      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v5
