name: Code Coverage
on: [ push, pull_request ]

jobs:
  codecov:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
      - name: Install direnv
        run: |
          curl -sfL https://direnv.net/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Load direnv
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"

      - name: Generate Coverage Report
        run: ./scripts/generate_coverage_report.sh coverage.out
      - name: Upload Unit Test Coverage to Codecov
        uses: codecov/codecov-action@v5
