name: GoReleaser
on:
  push:
    # run only against tags
    tags: [ '*' ]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Fetch All Tags
        run: git fetch --force --tags
      - name: Install direnv
        run: |
          curl -sfL https://direnv.net/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Load direnv
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"

      - name: Run GoReleaser
        run: nix develop -c goreleaser release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
