name: GoReleaser
on:
  push:
    # run only against tags
    tags: [ '*' ]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Enter direnv
        uses: ./.github/actions/enter-direnv
      - name: Cache Go Modules
        uses: actions/setup-go@v6

      - name: Run GoReleaser
        run: goreleaser release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
