name: Lint

on: [pull_request]

jobs:
  review:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repostitory
        uses: actions/checkout@v2
      - name: Lint Project
        uses: reviewdog/action-golangci-lint@v1
        with:
          reporter: github-pr-review
