name: Lint
on:
  pull_request:
  push:
    branches: [ v2 ]

permissions:
  contents: read

jobs:
  review:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Enter Direnv
        uses: ./.github/actions/enter-direnv

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          install-mode: none
