name: Test
on: [ push, pull_request ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Enter Direnv
        uses: ./.github/actions/enter-direnv
      - name: Cache Go Modules
        uses: actions/setup-go@v6

      - name: Run Unit Tests
        run: go test -race ./...
