name: Test
on: [ push, pull_request ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
      - name: Restore and Save Nix Store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}-${{ hashFiles('flake.nix') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}-
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          # created more than this number of seconds ago
          purge-created: 0
          # or, last accessed more than this number of seconds ago
          # relative to the start of the `Post Restore and save Nix store` phase
          purge-last-accessed: 0
          purge-primary-key: never
      - name: Install direnv
        run: |
          curl -sfL https://direnv.net/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Load direnv
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"
      - name: Cache Go Modules
        uses: actions/setup-go@v6

      - name: Run Unit Tests
        run: go test -race ./...
